[workspace]
[package]
name = "ipa"
version = "0.1.0"
edition = "2024"

[dependencies]
cli = { path = "../../cli" }
ark-std = "0.5.0"
ark-ff =  { git = "https://github.com/arkworks-rs/algebra.git" }
backend = { path = "../../backend" }
lang = { path = "../../lang" }
rand = { version = "0.8", features = ["std"] }