//! Backend of the analyses crate: Gröbner basis computation and polynomial
//! reduction, owned by the [`GbBackend`] trait.
//!
//! The backend owns all leading-term / ordering logic. Analyses hand the
//! backend an ideal and a [`MonoOrder`](crate::frontend::MonoOrder) and receive
//! a [`GbBasis`] or a reduced polynomial.

pub mod ark_gb;
pub mod singular;

use crate::Var;
use crate::frontend::{BackendError, BlockKind, MonoOrder, Polynomial};
use ark_ff::PrimeField;
use share::Set;

/// User-selectable Gröbner-basis backend.
///
/// Passed to analysis constructors to choose the GB engine. Default is
/// [`GbBackendKind::ArkGb`].
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum GbBackendKind {
    /// ark-gb (default). Supports GrevLex, 2-block GrevLex elim, and
    /// Lex-then-GrevLex tiered orderings.
    #[default]
    ArkGb,
    /// Singular CLI. Supports arbitrary Lex/GrevLex block combinations,
    /// including GrevLex-then-Lex. Requires `Singular` on `PATH`.
    Singular,
}

impl GbBackendKind {
    /// Instantiate the backend.
    pub fn build<F: PrimeField>(self) -> Box<dyn GbBackend<F>> {
        match self {
            GbBackendKind::ArkGb => Box::new(ark_gb::ArkGb::<F>::default()),
            GbBackendKind::Singular => Box::new(singular::Singular::<F>::default()),
        }
    }
}

/// An order-free Gröbner basis: the basis polynomials plus the ordering they
/// were computed under (so [`GbBackend::reduce`] can reuse it).
#[derive(Clone, Debug)]
pub struct GbBasis<F: ark_ff::PrimeField> {
    pub polys: Vec<Polynomial<F>>,
    pub order: MonoOrder,
}

impl<F: ark_ff::PrimeField> GbBasis<F> {
    pub fn empty(order: MonoOrder) -> Self {
        GbBasis {
            polys: Vec::new(),
            order,
        }
    }

    pub fn is_empty(&self) -> bool {
        self.polys.is_empty()
    }

    pub fn len(&self) -> usize {
        self.polys.len()
    }

    pub fn iter(&self) -> impl Iterator<Item = &Polynomial<F>> {
        self.polys.iter()
    }

    pub fn vars(&self) -> Set<Var> {
        self.polys
            .iter()
            .flat_map(|p| p.vars().into_iter())
            .collect()
    }

    /// Returns `true` if the basis is the unit ideal (contains a nonzero
    /// constant polynomial).
    pub fn is_unit(&self) -> bool {
        self.polys.iter().any(|p| p.is_constant() && !p.is_zero())
    }

    /// The ordering this basis was computed under.
    pub fn order(&self) -> &MonoOrder {
        &self.order
    }
}

/// A Gröbner-basis backend.
///
/// Implementations own all monomial-ordering logic. The frontend never reads a
/// leading term; it delegates both basis computation and reduction here.
pub trait GbBackend<F: PrimeField> {
    /// Compute the reduced Gröbner basis of the ideal generated by `ideal`,
    /// under `order`.
    fn compute_gb(
        &self,
        ideal: Vec<Polynomial<F>>,
        order: &MonoOrder,
    ) -> Result<GbBasis<F>, BackendError>;

    /// Reduce `p` modulo `basis` (using the ordering `basis` was computed
    /// under). Returns the remainder.
    fn reduce(&self, p: Polynomial<F>, basis: &GbBasis<F>) -> Polynomial<F>;
}

/// Order-aware polynomial reduction: reduces `p` modulo `basis_polys` under
/// `order`. Returns the remainder `r` such that no term in `r` is divisible
/// by the leading term of any basis polynomial.
pub fn reduce<F: PrimeField>(
    p: Polynomial<F>,
    basis_polys: &[Polynomial<F>],
    order: &MonoOrder,
) -> Polynomial<F> {
    use crate::frontend::Monomial;
    use std::collections::HashMap;

    // Collect all PRefs from the input polynomials.
    let all_vars: Vec<Var> = {
        let mut vs: Vec<Var> = basis_polys.iter().flat_map(|p| p.vars()).collect();
        vs.extend(p.vars());
        vs.sort();
        vs.dedup();
        vs
    };

    // Shared block-var assignment (same logic as MonoOrder::compare).
    let block_assignment = order.block_var_assignment(&all_vars);

    // Block-aware sort key: iterate blocks and append ordering components per
    // block. Lexicographic comparison of the Vec gives the correct ordering.
    let sort_key = |m: &Monomial| -> Vec<i64> {
        let mut key = Vec::new();
        for (kind, bv) in &block_assignment {
            let exps: Vec<i64> = bv.iter().map(|v| m.powers_for(v) as i64).collect();
            match kind {
                BlockKind::Lex => {
                    key.extend(exps.into_iter().map(|e| -e));
                }
                BlockKind::GrevLex => {
                    let deg: i64 = exps.iter().sum();
                    key.push(-deg);
                    key.extend(exps.iter().rev());
                }
            }
        }
        key
    };

    // Precompute leading terms of basis polynomials.
    type Reducer<F> = (F, Monomial, Vec<(Monomial, F)>);
    let reducers: Vec<Reducer<F>> = basis_polys
        .iter()
        .filter(|p| !p.is_zero())
        .filter_map(|g| {
            let mut terms: Vec<(Monomial, F)> =
                g.terms.iter().map(|(m, c)| (m.clone(), *c)).collect();
            terms.sort_by_key(|a| sort_key(&a.0));
            let (lt_mono, lt_coeff) = terms.first()?;
            Some((*lt_coeff, lt_mono.clone(), terms))
        })
        .collect();

    // Work set: HashMap for O(1) merge during reduction steps.
    let mut work: HashMap<Monomial, F> =
        p.terms.into_iter().filter(|(_, c)| !c.is_zero()).collect();
    let mut remainder: Vec<(Monomial, F)> = Vec::new();

    while !work.is_empty() {
        // Find the leading term: the monomial with the smallest sort key.
        let (lt_mono, lt_coeff) = work
            .iter()
            .min_by_key(|(m, _)| sort_key(m))
            .expect("work is non-empty");
        let lt_mono = lt_mono.clone();
        let lt_coeff = *lt_coeff;

        let found = reducers
            .iter()
            .find(|(_, g_lt, _)| lt_mono.is_divided(g_lt));

        if let Some((g_lc, g_lt, g_terms)) = found {
            let multiplier_term = (lt_mono.clone() / g_lt.clone()).expect("divisibility checked");
            let multiplier_scalar = lt_coeff * (*g_lc).inverse().expect("leading coeff nonzero");
            // Subtract multiplier_scalar * multiplier_term * g from work.
            // The reducer's LT term cancels our LT to 0 (removed by retain).
            for (g_term, g_coeff) in g_terms {
                let new_term = g_term.clone() * multiplier_term.clone();
                let new_coeff = *g_coeff * multiplier_scalar;
                let entry = work.entry(new_term).or_insert(F::zero());
                *entry -= new_coeff;
            }
            work.retain(|_, c| !c.is_zero());
        } else {
            // No division: move LT to remainder.
            work.remove(&lt_mono);
            remainder.push((lt_mono, lt_coeff));
        }
    }

    let terms = remainder.into_iter().collect();
    Polynomial { terms }
}

#[cfg(test)]
mod tests;
