//! Backend of the analyses crate: Gröbner basis computation and polynomial
//! reduction, owned by the [`GbBackend`] trait.
//!
//! The backend owns all leading-term / ordering logic. Analyses hand the
//! backend an ideal and a [`MonoOrder`](crate::frontend::MonoOrder) and receive
//! a [`GbBasis`] or a reduced polynomial.

pub mod ark_gb;
pub mod singular;

use crate::frontend::{BlockKind, MonoOrder, Polynomial, UnsupportedMonoOrder};
use ark_ff::Field;
use backend::ArkConfig;
use graph::PRef;
use share::Set;

/// An order-free Gröbner basis: the basis polynomials plus the ordering they
/// were computed under (so [`GbBackend::reduce`] can reuse it).
#[derive(Clone, Debug)]
pub struct GbBasis<F: ark_ff::Field> {
    pub polys: Vec<Polynomial<F>>,
    pub order: MonoOrder,
}

impl<F: ark_ff::Field> GbBasis<F> {
    pub fn empty(order: MonoOrder) -> Self {
        GbBasis {
            polys: Vec::new(),
            order,
        }
    }

    pub fn is_empty(&self) -> bool {
        self.polys.is_empty()
    }

    pub fn len(&self) -> usize {
        self.polys.len()
    }

    pub fn iter(&self) -> impl Iterator<Item = &Polynomial<F>> {
        self.polys.iter()
    }

    pub fn vars(&self) -> Set<PRef> {
        self.polys
            .iter()
            .flat_map(|p| p.vars().into_iter())
            .collect()
    }

    /// Returns `true` if the basis is the unit ideal (contains a nonzero
    /// constant polynomial).
    pub fn is_unit(&self) -> bool {
        self.polys.iter().any(|p| p.is_constant() && !p.is_zero())
    }

    /// The ordering this basis was computed under.
    pub fn order(&self) -> &MonoOrder {
        &self.order
    }
}

/// A Gröbner-basis backend.
///
/// Implementations own all monomial-ordering logic. The frontend never reads a
/// leading term; it delegates both basis computation and reduction here.
pub trait GbBackend<C: ArkConfig> {
    /// Compute the reduced Gröbner basis of the ideal generated by `ideal`,
    /// under `order`. `w` is the packed monomial width (backend-specific).
    fn compute_gb(
        &self,
        ideal: Vec<Polynomial<C::F>>,
        order: &MonoOrder,
        w: usize,
    ) -> Result<GbBasis<C::F>, UnsupportedMonoOrder>;

    /// Reduce `p` modulo `basis` (using the ordering `basis` was computed
    /// under). Returns the remainder.
    fn reduce(&self, p: Polynomial<C::F>, basis: &GbBasis<C::F>) -> Polynomial<C::F>;
}

/// Order-aware polynomial reduction: reduces `p` modulo `basis_polys` under
/// `order`. Returns the remainder `r` such that no term in `r` is divisible
/// by the leading term of any basis polynomial.
pub fn reduce<F: Field>(
    p: Polynomial<F>,
    basis_polys: &[Polynomial<F>],
    order: &MonoOrder,
) -> Polynomial<F> {
    use crate::frontend::Monomial;

    // Build a variable ordering from the MonoOrder: a Vec<PRef> where index 0
    // has the highest elimination priority. When a block has `vars: None`,
    // collect remaining vars from the input polynomials (sorted by PRef::Ord).
    let mut var_order: Vec<PRef> = Vec::new();
    let mut seen = std::collections::HashSet::new();
    let all_vars: Vec<PRef> = {
        let mut vs: Vec<PRef> = basis_polys.iter().flat_map(|p| p.vars()).collect();
        vs.extend(p.vars());
        vs.sort();
        vs.dedup();
        vs
    };
    for block in order.blocks() {
        if let Some(vs) = &block.vars {
            for v in vs {
                if seen.insert(v.reference) {
                    var_order.push(v.clone());
                }
            }
        } else {
            // "Remaining vars" block: add all vars not yet seen.
            for v in &all_vars {
                if seen.insert(v.reference) {
                    var_order.push(v.clone());
                }
            }
        }
    }
    // Add any vars not covered by any block.
    for v in &all_vars {
        if !seen.contains(&v.reference) {
            var_order.push(v.clone());
            seen.insert(v.reference);
        }
    }
    let is_lex = matches!(
        order.blocks().first().map(|b| &b.kind),
        Some(BlockKind::Lex)
    );

    // Compute a sort key for a monomial: a Vec of values that, when compared
    // lexicographically, gives the correct monomial ordering.
    // For Lex: exponents in var_order (higher = leading = sorts first → we reverse).
    // For GrevLex: (total_degree, then revlex) — higher degree = leading.
    // We use a key where "smaller = leading" (first in sorted order).
    let sort_key = |m: &Monomial| -> Vec<i64> {
        let exps: Vec<i64> = var_order.iter().map(|v| m.powers_for(v) as i64).collect();
        if is_lex {
            // Lex: higher exponent on earlier var = leading = sorts first.
            // Negate so that higher exponent → smaller key → sorts first.
            exps.into_iter().map(|e| -e).collect()
        } else {
            // GrevLex: higher total degree = leading = sorts first.
            // Then at the rightmost differing var, smaller exponent = leading.
            let deg: i64 = exps.iter().sum();
            let mut key = vec![-deg]; // higher degree → smaller → first
            // Right-to-left: smaller exponent = leading = smaller key.
            for e in exps.iter().rev() {
                key.push(*e);
            }
            key
        }
    };

    // Precompute leading terms of basis polynomials.
    type Reducer<F> = (F, Monomial, Vec<(Monomial, F)>);
    let reducers: Vec<Reducer<F>> = basis_polys
        .iter()
        .filter(|p| !p.is_zero())
        .filter_map(|g| {
            let mut terms: Vec<(Monomial, F)> =
                g.terms.iter().map(|(m, c)| (m.clone(), *c)).collect();
            terms.sort_by_key(|a| sort_key(&a.0));
            let (lt_mono, lt_coeff) = terms.first()?;
            Some((*lt_coeff, lt_mono.clone(), terms))
        })
        .collect();

    // Convert p to a sorted Vec.
    let mut work: Vec<(Monomial, F)> = p.terms.into_iter().collect();
    work.sort_by_key(|a| sort_key(&a.0));
    let mut remainder: Vec<(Monomial, F)> = Vec::new();

    while !work.is_empty() {
        let (lt_mono, lt_coeff) = work[0].clone();
        if lt_coeff.is_zero() {
            work.remove(0);
            continue;
        }

        let found = reducers
            .iter()
            .find(|(_, g_lt, _)| lt_mono.is_divided(g_lt));

        if let Some((g_lc, g_lt, g_terms)) = found {
            let multiplier_term = (lt_mono.clone() / g_lt.clone()).expect("divisibility checked");
            let multiplier_scalar = lt_coeff * (*g_lc).inverse().expect("leading coeff nonzero");
            // Subtract multiplier_scalar * multiplier_term * g from work.
            let mut new_terms: Vec<(Monomial, F)> = Vec::new();
            for (g_term, g_coeff) in g_terms {
                let new_term = g_term.clone() * multiplier_term.clone();
                let new_coeff = *g_coeff * multiplier_scalar;
                new_terms.push((new_term, new_coeff));
            }
            // Merge new_terms into work (subtract).
            for (nt, nc) in new_terms {
                if let Some(pos) = work.iter().position(|(m, _)| *m == nt) {
                    work[pos].1 -= nc;
                } else {
                    work.push((nt, -nc));
                }
            }
            // Remove zeros and re-sort.
            work.retain(|(_, c)| !c.is_zero());
            work.sort_by_key(|a| sort_key(&a.0));
        } else {
            // No division: move LT to remainder.
            work.remove(0);
            remainder.push((lt_mono, lt_coeff));
        }
    }

    let terms = remainder.into_iter().collect();
    Polynomial { terms }
}

#[cfg(test)]
mod tests;
