[workspace]
members = [ "lang", "runtime", "share" , "graph", "backend"]
exclude = [ "sumcheck_compare" ]
default-members = [ ".", "lang", "runtime", "share" , "graph", "backend"]
resolver = "2"

[workspace.dependencies]
ark-std = { version = "0.6.0", features = ["parallel"] }
ark-ff = { version = "0.6.0", features = ["parallel"] }
ark-ec = { version = "0.6.0", features = ["parallel"] }
ark-poly = { version = "0.6.0", features = ["parallel"] }
ark-serialize = { version = "0.6.0", features = ["parallel"] }
ark-bls12-377 = { version = "0.6.0" }
ark-bls12-381 = { version = "0.6.0" }
ark-ed-on-cp6-782 = { version = "0.6.0" }
ark-bn254 = { version = "0.6.0" }
ark-mnt4-298 = { version = "0.6.0" }
ark-mnt4-753 = { version = "0.6.0" }
ark-pallas = { version = "0.6.0" }
ark-secp256k1 = { version = "0.6.0" }
ark-curve25519 = { version = "0.6.0" }
ark-ed25519 = { version = "0.6.0" }
ark-vesta = { version = "0.6.0" }
ark-relations = { version = "0.6.0" }
ark-groth16 = { version = "0.6.0" }
ark-gb = { path = "vendor/ark-gb" }
spongefish = { version = "0.7.1", features = ["ark-ff", "ark-ec"] }

[package]
name = "zippel"
version = "0.1.0"
edition = "2024"

[dependencies]
backend = { path = "./backend" }
share = { path = "./share" }
lang = { path = "./lang" }
graph = { path = "./graph" }
runtime = { path = "./runtime" }
env_logger = "0.11.8"
log = "0.4.27"
ark-std = { workspace = true }
ark-ff = { workspace = true }
ark-poly = { workspace = true }
rand = { version = "0.8", features = ["std"] }
spongefish = { workspace = true }

[dev-dependencies]
tempfile = "3.10"
criterion = "0.5"
ark-bls12-381 = { workspace = true }
ark-relations = { workspace = true }
ark-groth16 = { workspace = true }
ark-ec = { workspace = true }
petgraph = "0.7.1"

[patch.crates-io]
ark-gb = { path = "vendor/ark-gb" }

[[bench]]
name = "graph_execution"
harness = false

[[bench]]
name = "groebner"
harness = false

[[bench]]
name = "groth16"
harness = false

[[example]]
name = "mle"
path = "examples/mle_example/main.rs"

[[example]]
name = "kzg"
path = "examples/kzg/main.rs"

[[example]]
name = "ipa"
path = "examples/ipa/main.rs"

[[example]]
name = "ipa_optimized"
path = "examples/ipa_optimized/main.rs"

[[example]]
name = "ipa_field"
path = "examples/ipa_field/main.rs"

[[example]]
name = "schnorr"
path = "examples/schnorr/main.rs"

[[example]]
name = "cp"
path = "examples/cp/main.rs"

[[example]]
name = "sumcheck"
path = "examples/sumcheck/main.rs"

[[example]]
name = "fft_interpolate"
path = "examples/fft_interpolate/main.rs"

[[example]]
name = "zerocheck"
path = "examples/zerocheck/main.rs"

[[example]]
name = "hadamard"
path = "examples/hadamard/main.rs"

[[example]]
name = "toy_record"
path = "examples/toy_record/main.rs"

[[example]]
name = "marginalize"
path = "examples/marginalize/main.rs"

[[example]]
name = "vpoly"
path = "examples/vpoly/main.rs"

[[example]]
name = "hyrax_pop"
path = "examples/hyrax_pop/main.rs"

[[example]]
name = "hyrax_podp"
path = "examples/hyrax_podp/main.rs"

[[example]]
name = "hyrax_ipa"
path = "examples/hyrax_ipa/main.rs"

[[example]]
name = "pedersen_eq"
path = "examples/pedersen_eq/main.rs"

[[example]]
name = "dory"
path = "examples/dory/main.rs"

[[example]]
name = "node_issue"
path = "examples/node_issue/main.rs"

[[example]]
name = "pst13"
path = "examples/pst13/main.rs"

[[example]]
name = "benchmark"
path = "examples/benchmark/main.rs"

[[example]]
name = "schnorr_no_random"
path = "examples/schnorr_no_random/main.rs"

[[example]]
name = "schnorr_and"
path = "examples/schnorr_and/main.rs"

[[example]]
name = "schnorr_and_two_verify"
path = "examples/schnorr_and_two_verify/main.rs"

[[example]]
name = "commitment_equality"
path = "examples/commitment_equality/main.rs"

[[example]]
name = "ex_hyrax_sum"
path = "examples/ex_hyrax_sum/main.rs"

[[example]]
name = "ex_pairing"
path = "examples/ex_pairing/main.rs"

[[example]]
name = "ex_rec"
path = "examples/ex_rec/main.rs"

[[example]]
name = "kzh"
path = "examples/kzh/main.rs"

[[example]]
name = "stdlib"
path = "examples/stdlib/main.rs"

[[example]]
name = "transcript_random"
path = "examples/transcript_random/main.rs"

[[example]]
name = "virtual_test"
path = "examples/virtual_test/main.rs"

[[example]]
name = "map_comp_bench"
path = "examples/map_comp_bench/main.rs"

[[example]]
name = "type_alias"
path = "examples/type_alias/main.rs"

[[example]]
name = "r1cs_sigma"
path = "examples/r1cs_sigma/main.rs"

[[example]]
name = "spartan"
path = "examples/spartan/main.rs"

[[example]]
name = "cds"
path = "examples/cds/main.rs"

[[example]]
name = "zk-kzg"
path = "examples/zk-kzg/main.rs"

[[example]]
name = "mle_sumcheck"
path = "examples/mle_sumcheck/main.rs"

[[example]]
name = "hyperplonk_zerocheck"
path = "examples/hyperplonk_zerocheck/main.rs"

[[example]]
name = "hyperplonk_productcheck"
path = "examples/hyperplonk_productcheck/main.rs"

[[example]]
name = "hyperplonk_multiset"
path = "examples/hyperplonk_multiset/main.rs"

[[example]]
name = "hyperplonk_permutation"
path = "examples/hyperplonk_permutation/main.rs"

[[example]]
name = "hyperplonk"
path = "examples/hyperplonk/main.rs"

[[example]]
name = "bccgp"
path = "examples/bccgp/main.rs"

[[example]]
name = "coin_proof"
path = "examples/coin_proof/main.rs"

[[example]]
name = "membership"
path = "examples/membership/main.rs"

[[example]]
name = "zeromorph_kzg"
path = "examples/zeromorph_kzg/main.rs"

[[example]]
name = "groth16"
path = "examples/groth16/main.rs"
