[package]
name = "backend"
version = "0.1.0"
edition.workspace = true

[dependencies]
ark-ec = { version = "0.6", features = ["parallel"] }
ark-serialize = { version = "0.6", features = ["parallel"] }
ark-bls12-381 = { version = "0.6" }
ark-bn254 = { version = "0.6" }
ark-mnt4-298 = { version = "0.6" }
ark-pallas = { version = "0.6" }
ark-secp256k1 = { version = "0.6" }
ark-curve25519 = { version = "0.6" }
ark-ed25519 = { version = "0.6" }
ark-vesta = { version = "0.6" }
ark-ff =  { version = "0.6", features = ["parallel"] }
ark-poly =  { version = "0.6", features = ["parallel"] }
ark-std = { version = "0.6.0", features = ["parallel"] }
spongefish =  { version = "0.7", features = ["ark-ff", "ark-ec"] }
rayon = "1.10.0"
rand = { version = "0.8", features = ["std"] }
num-bigint = "0.4.6"
zeroize = "1.8.1"
thiserror = "2.0.11"
share = { path = "../share" }
lang = { path = "../lang" }
serde = { version = "1.0.219", features = ["derive"] }
petgraph = "0.7.1"
hashconsing = "1.6"
lazy_static = "1.5"

[dev-dependencies]
ark-std = "0.6.0"
arbitrary = { version = "1.4.1", features = ["derive"] }
arbtest = "0.3.2"

