[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-ec = { git = "https://github.com/arkworks-rs/algebra.git", features = ["parallel"] }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra.git", features = ["parallel"] }
ark-bls12-377 = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-bls12-381 = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-ed-on-cp6-782 = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-bn254 = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-mnt4-298 = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-mnt4-753 = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-pallas = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-secp256k1 = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-curve25519 = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-ed25519 = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-vesta = { git = "https://github.com/arkworks-rs/algebra.git" }
ark-ff =  { git = "https://github.com/arkworks-rs/algebra.git", features = ["parallel"] }
ark-poly =  { git = "https://github.com/arkworks-rs/algebra.git", features = ["parallel"] }
ark-std = { version = "0.6.0", features = ["parallel"] }
spongefish =  { git = "https://github.com/arkworks-rs/spongefish.git", branch = "main", features = ["ark-ff", "ark-ec"] }
rayon = "1.10.0"
rand = { version = "0.8", features = ["std"] }
num-bigint = "0.4.6"
zeroize = "1.8.1"
thiserror = "2.0.11"
share = { path = "../share" }
lang = { path = "../lang" }
serde = { version = "1.0.219", features = ["derive"] }
petgraph = "0.7.1"
hashconsing = "1.6"
lazy_static = "1.5"

[dev-dependencies]
ark-std = "0.6.0"
arbitrary = { version = "1.4.1", features = ["derive"] }
arbtest = "0.3.2"

