[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.10.0"
crossbeam-channel = "0.5"
rand = { version = "0.8", features = ["std"] }
petgraph = "0.7.1"
thiserror = "2.0.11"
graph = { path = "../graph" }
share = { path = "../share" }
lang = { path = "../lang" }
backend = { path = "../backend" }
log = "0.4.27"
spongefish =  { version = "0.7", features = ["ark-ff", "ark-ec"] }
blake3 = "1"

[dev-dependencies]
arbitrary = { version = "1.4.1", features = ["derive"] }
arbtest = "0.3.2"


