[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-ec = { version = "0.5.0" }
ark-bls12-377 = { version = "0.5.0" }
ark-bls12-381 = { version = "0.5.0" }
ark-ed-on-cp6-782 = { version = "0.5.0" }
ark-bn254 = { version = "0.5.0" }
ark-mnt4-298 = { version = "0.5.0" }
ark-mnt4-753 = { version = "0.5.0" }
ark-pallas = { version = "0.5.0" }
ark-secp256k1 = { version = "0.5.0" }
ark-curve25519 = { version = "0.5.0" }
lang = { version = "0.1.0", path = "../lang" }
ark-vesta = "0.5.0"
