[package]
name = "graph"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.10.0"
num-bigint = "0.4.6"
petgraph = "0.7.1"
thiserror = "2.0.11"
backend = { path = "../backend" }
share = { path = "../share" }
lang = { path = "../lang" }
ark-gb = { workspace = true }
ark-ff = { workspace = true }
ark-poly = { workspace = true }
ark-ec = { workspace = true }
ark-serialize = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-std = { workspace = true }
log = "0.4.27"
rand = { version = "0.8", features = ["std"] }
spongefish = { workspace = true }
itertools = "0.14.0"
hashconsing = "1.6"

[dev-dependencies]
arbitrary = { version = "1.4.1", features = ["derive"] }
arbtest = "0.3.2"
serial_test = "3.2.0"
