[package]
name = "graph"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.10.0"
petgraph = "0.7.1"
thiserror = "2.0.11"
backend = { path = "../backend" }
share = { path = "../share" }
lang = { path = "../lang" }
ark-ff = { version = "0.6", features = ["parallel"] }
ark-poly = { version = "0.6", features = ["parallel"] }
ark-bls12-381 = { version = "0.6" }
ark-std = { version = "0.6.0", features = ["parallel"] }
log = "0.4.27"
rand = { version = "0.8", features = ["std"] }
spongefish = { version = "0.7", features = [
    "ark-ff",
    "ark-ec",
] }

[dev-dependencies]
arbitrary = { version = "1.4.1", features = ["derive"] }
arbtest = "0.3.2"
serial_test = "3.2.0"
