version: 2.1
jobs:
  test:
    machine:
      image: ubuntu-2204:2024.05.1
    steps:
      - checkout
      - run: |
          docker pull elefthei/zippel:latest
          docker run -v .:/app elefthei/zippel:latest
  docker:
    machine:
      image: ubuntu-2204:2024.05.1
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          docker build -t elefthei/zippel:latest .
          docker push elefthei/zippel:latest

workflows:
  test:
    jobs:
      - docker
      - test
