//! `GroebnerBasis<F, T>` plus production polynomial-reduction helpers.
//!
//! The public Buchberger entry points (`buchberger`, `reduce_groebner_basis`,
//! `buchberger_and_reduce`) dispatch through [`Monomial::compute_reduced_gb`],
//! which both `GrevLexTerm` and `ElimTerm` override to route into the external
//! `ark-gb` crate (~10000× speedup on Katsura/Cyclic-n; see
//! `analyses::groebner::ark_gb_adapter`). The original in-tree Buchberger is
//! retained as `#[cfg(test)]`-only `legacy_*` methods so the speedup bench can
//! still A/B-time them against ark-gb — it's not compiled into release.

use ark_ff::Field;
use std::fmt;
use std::ops::Index;

use crate::PRef;
use crate::analyses::groebner::{Monomial, SparsePolynomial};
use rayon::prelude::*;
use share::Set;

#[cfg(test)]
use log::debug;
#[cfg(test)]
use std::collections::{HashSet, VecDeque};

/// A struct representing a Gröbner basis.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GroebnerBasis<F: Field, T: Monomial> {
    pub basis: Vec<SparsePolynomial<F, T>>,
    pub num_vars: usize,
}

impl<F: Field, T: Monomial> Index<usize> for GroebnerBasis<F, T> {
    type Output = SparsePolynomial<F, T>;

    fn index(&self, index: usize) -> &Self::Output {
        &self.basis[index]
    }
}

impl<F: Field, T: Monomial> IntoIterator for GroebnerBasis<F, T> {
    type Item = SparsePolynomial<F, T>;
    type IntoIter = std::vec::IntoIter<SparsePolynomial<F, T>>;

    fn into_iter(self) -> Self::IntoIter {
        self.basis.into_iter()
    }
}

impl<F: Field, T: Monomial> GroebnerBasis<F, T> {
    pub fn new(num_vars: usize, basis: Vec<SparsePolynomial<F, T>>) -> Self {
        Self { basis, num_vars }
    }

    pub fn empty(num_vars: usize) -> Self {
        Self {
            basis: Vec::new(),
            num_vars,
        }
    }

    pub fn contains_poly(&self, poly: &SparsePolynomial<F, T>) -> bool {
        let poly = poly.clone();
        let rem = self.reduce(poly);
        rem.is_zero() // If the reduction is zero, poly is in the ideal generated by the basis
    }

    pub fn contains(&self, other: &Self) -> bool {
        other.basis.iter().all(|p| self.contains_poly(p))
    }

    pub fn is_empty(&self) -> bool {
        self.basis.is_empty()
    }

    pub fn len(&self) -> usize {
        self.basis.len()
    }

    pub fn iter(&self) -> impl Iterator<Item = &SparsePolynomial<F, T>> {
        self.basis.iter()
    }

    pub fn push(&mut self, poly: SparsePolynomial<F, T>) {
        self.basis.push(poly);
    }

    pub fn eliminate_var<FF: Fn(&PRef) -> bool>(&mut self, f: &FF) {
        self.basis.retain(|p| p.vars().find(|v| f(v)).is_none());
    }

    pub fn eliminate_monomial<FF: Fn(&T) -> bool>(&mut self, f: &FF) {
        self.basis.retain(|p| p.terms.iter().any(|(t, _)| !f(t)));
    }

    pub fn iter_mut(&mut self) -> impl Iterator<Item = &mut SparsePolynomial<F, T>> {
        self.basis.iter_mut()
    }

    pub fn vars(&self) -> Set<PRef> {
        self.basis
            .iter()
            .flat_map(|p| p.vars().into_iter())
            .collect()
    }

    /// Reduces polynomial `p` with respect to the basis `G`.
    /// Returns the remainder `r` such that `p = sum(q_i * g_i) + r`, and no term in `r`
    /// is divisible by the leading term of any `g_i` in `G`.
    /// Assumes `G` does not contain the zero polynomial.
    pub fn reduce(&self, mut p: SparsePolynomial<F, T>) -> SparsePolynomial<F, T> {
        let mut remainder = SparsePolynomial::zero();

        // The basis against which we reduce. Filter out zeros once.
        let reducers: Vec<_> = self.basis.iter().filter(|poly| !poly.is_zero()).collect();

        // While p is not zero
        while let Some((p_lc, p_lt)) = p.leading_term() {
            let found_divisor = reducers.par_iter().find_any(|g| {
                if let Some((_g_lc, g_lt)) = g.leading_term() {
                    p_lt.is_divided(&g_lt)
                } else {
                    false
                }
            });

            if let Some(g) = found_divisor {
                let (g_lc, g_lt) = g.leading_term().unwrap();
                let multiplier_term =
                    (p_lt / g_lt).expect("Division should succeed if is_divided is true");
                let multiplier_scalar = p_lc
                    * g_lc
                        .inverse()
                        .expect("Leading coefficient must be invertible");
                let to_subtract = g.mul_by_term_and_scalar(multiplier_scalar, &multiplier_term);
                p -= to_subtract;
            } else {
                // No division occurred, move LT(p) to the remainder.
                let (lt, lc) = p.terms.pop_first().unwrap(); // BTreeMap specific method
                remainder.terms.insert(&lt, &lc); // Add to remainder
            }
        }

        remainder
    }

    /// Group-parallel pair selection (used only by `legacy_buchberger`).
    #[cfg(test)]
    fn pairs_select(&self, pairs: &mut VecDeque<(usize, usize)>) -> Vec<(usize, usize)> {
        let num_threads = std::thread::available_parallelism()
            .map(|n| n.get())
            .unwrap_or(1)
            .saturating_sub(1)
            .max(2);

        let mut selected = Vec::new();
        for _ in 0..num_threads {
            if let Some((i, j)) = pairs.pop_front() {
                if i < self.len() && j < self.len() {
                    selected.push((i, j));
                }
            } else {
                break;
            }
        }
        selected
    }

    /// In-tree Buchberger implementation. Test-only — production paths
    /// dispatch through [`Monomial::compute_reduced_gb`] which routes into
    /// ark-gb. Retained so the speedup bench can A/B against ark-gb.
    #[cfg(test)]
    pub(crate) fn legacy_buchberger(&self) -> Self {
        if self.basis.is_empty() {
            return Self::empty(self.num_vars);
        }

        // Initialize with non-zero polynomials
        let basis_nonzero = self
            .basis
            .iter()
            .filter(|p| !p.is_zero())
            .cloned()
            .collect();

        let mut g: Self = Self::new(self.num_vars, basis_nonzero);

        // Initialize the set of critical pairs (indices into G)
        let mut pairs: VecDeque<(usize, usize)> = VecDeque::new();
        let mut seen = HashSet::new();

        for i in 0..g.len() {
            for j in (i + 1)..g.len() {
                pairs.push_back((i, j));
            }
        }

        while !pairs.is_empty() {
            let ps = g.pairs_select(&mut pairs);

            // Add pairs to seen set
            seen.extend(ps.iter().map(|(i, j)| (*i, *j)));

            let reduced_ps: Vec<SparsePolynomial<F, T>> = ps
                .par_iter()
                .filter_map(|&(i, j)| {
                    // Ensure indices are still valid (G might grow)
                    if i >= g.len() || j >= g.len() {
                        return None;
                    }

                    let g_i = &g[i];
                    let g_j = &g[j];

                    debug!("Processing pair ({}, {})", i, j); // Debug output

                    // Compute S-polynomial
                    let s_poly = g_i.s_poly(g_j);

                    if s_poly.is_zero() {
                        // S-polynomial reduced to zero immediately
                        debug!("  S(G[{}], G[{}]) = 0", i, j);
                        return None;
                    }

                    // Reduce the S-polynomial with respect to the current basis G
                    let s_reduced = g.reduce(s_poly);

                    // If the reduced S-polynomial is not zero, return it
                    if !s_reduced.is_zero() {
                        debug!("  S(G[{}], G[{}]) reduces to non-zero polynomial.", i, j);
                        Some(s_reduced)
                    } else {
                        debug!("  S(G[{}], G[{}]) reduces to 0", i, j);
                        None
                    }
                })
                .collect();

            // Add new polynomials and generate pairs
            for s_reduced in reduced_ps {
                let k = g.len(); // Index of the polynomial we're about to add
                g.push(s_reduced);

                // Add new critical pairs involving the new polynomial h (index k)
                // with all existing polynomials in G (indices 0 to k-1)
                for l in 0..k {
                    if !Self::skip_pair(l, k, &g, &seen) {
                        pairs.push_back((l, k));
                    }
                }
            }
        }

        // Return the computed Gröbner basis (not necessarily minimal/reduced yet)
        g
    }

    /// Buchberger's criteria (https://www.andrew.cmu.edu/course/15-355/lectures/lecture11.pdf).
    /// Only used by `legacy_buchberger`.
    #[cfg(test)]
    fn skip_pair(
        l: usize,
        k: usize,
        g: &GroebnerBasis<F, T>,
        seen: &HashSet<(usize, usize)>,
    ) -> bool {
        // Buchberger's first criterion: skip pairs (l, k) if their leading monomials are coprime (LCM is product)
        let lt_l = g[l].leading_term().map(|(_, m)| m);
        let lt_k = g[k].leading_term().map(|(_, m)| m);
        if let (Some(ml), Some(mk)) = (lt_l, lt_k) {
            // Buchberger's first criterion: skip pairs (l, k) if their leading monomials are coprime (LCM is product)
            if ml.is_coprime(&mk) {
                return true;
            }

            // Buchberger's second criterion: skip pairs (l, k) if there exists an [i] such that LCM(LT(l), LT(k)) is a multiple of LT(i)
            // and (l, i) and (i, k) have been seen before
            return (0..g.len()).into_par_iter().any(|i| {
                if let Some(lt_i) = g[i].leading_term().map(|(_, m)| m)
                    && ml.lcm(&mk).is_divided(&lt_i)
                    && seen.contains(&(l, i))
                    && seen.contains(&(i, k))
                {
                    return true;
                }
                false
            });
        }
        false
    }

    /// Reduces a computed Gröbner basis to a minimal, reduced Gröbner basis.
    /// 1. Makes all polynomials monic.
    /// 2. Removes redundant polynomials (whose LT is divisible by another's LT).
    /// 3. Reduces each polynomial against the others.
    ///
    /// Test-only — production paths dispatch into ark-gb.
    #[cfg(test)]
    pub(crate) fn legacy_reduce_groebner_basis(&mut self) {
        // --- Step 0: Calculate the number of variables ---
        let num_vars = self.num_vars;

        // --- Step 1: Make polynomials monic & initial cleanup ---
        let mut g_monic = GroebnerBasis::empty(num_vars);
        for p in self.iter() {
            if p.is_zero() {
                continue;
            } // Remove zero polynomials

            if let Some((lc, _)) = p.leading_term() {
                let lc_inv = lc
                    .inverse()
                    .expect("Leading coefficient must be invertible in a Field for non-zero poly");

                // Multiply the entire polynomial by lc_inv
                let mut monic_p = SparsePolynomial::zero(); // Start fresh
                for (term, coeff) in p.terms.iter() {
                    monic_p.terms.insert(term, &(*coeff * lc_inv));
                }

                // Ensure it's still not zero after making monic (unlikely but possible with weird fields)
                if !monic_p.is_zero() {
                    g_monic.push(monic_p);
                }
            }
            // else: p was zero, already skipped
        }
        *self = g_monic; // Replace G with the monic version

        // Sort by leading term order (important for the next step)
        // This assumes the Ord trait on Monomial defines the term order used.
        self.basis.sort_unstable_by(|p1, p2| {
            let lt1 = p1.leading_term().map(|(_, t)| t);
            let lt2 = p2.leading_term().map(|(_, t)| t);
            lt1.cmp(&lt2) // Compare leading terms
        });

        // --- Step 2: Remove polynomials whose leading term is divisible by another's LT ---
        // This step creates a "minimal" basis (but not yet "reduced")
        let mut g_minimal = GroebnerBasis::empty(num_vars);
        let mut discarded = vec![false; self.len()];

        for i in 0..self.len() {
            if discarded[i] {
                continue;
            }
            let lt_i = self[i].leading_term().unwrap().1; // Safe unwrap: non-zero polys

            for j in (i + 1)..self.len() {
                if discarded[j] {
                    continue;
                }
                let lt_j = self[j].leading_term().unwrap().1;

                // If LT(j) is_divided LT(i), mark j for removal (since G is sorted by LT)
                // Note: If LT(i) == LT(j), this should theoretically not happen if basis elements are distinct
                // and monic, but we handle it by discarding j.
                if lt_j.is_divided(&lt_i) {
                    discarded[j] = true;
                }
                // We don't need to check if LT(i) is_divided LT(j) because G is sorted by LT.
            }
        }

        // Collect non-discarded polynomials
        for i in 0..self.len() {
            if !discarded[i] {
                g_minimal.push(self[i].clone()); // Clone necessary as we modify below
            }
        }
        *self = g_minimal; // Update G

        // --- Step 3: Inter-reduce the basis (Full Reduction) ---
        // For each g in G, reduce it by G \ {g}.
        let mut g_reduced = GroebnerBasis::new(num_vars, Vec::with_capacity(self.len()));
        for i in 0..self.len() {
            let current_g = self[i].clone();

            // Create basis for reduction: G excluding current_g
            let mut reduction_basis = GroebnerBasis::empty(num_vars);
            for j in 0..self.len() {
                if i != j {
                    reduction_basis.push(self[j].clone());
                }
            }

            // Reduce current_g by the rest of the basis
            let reduced_g = reduction_basis.reduce(current_g);

            // Add the fully reduced polynomial (it should still be monic and non-zero
            // unless the basis was {c} -> {1} and reduction makes it 0, which we filter)
            if !reduced_g.is_zero() {
                g_reduced.push(reduced_g);
            }
        }

        // Final sort (optional, but good practice)
        g_reduced.basis.sort_unstable_by(|p1, p2| {
            let lt1 = p1.leading_term().map(|(_, t)| t);
            let lt2 = p2.leading_term().map(|(_, t)| t);
            lt1.cmp(&lt2)
        });

        *self = g_reduced;
    }

    /// Compute the reduced Gröbner basis. Dispatches via
    /// [`Monomial::compute_reduced_gb`] — the `GrevLexTerm` override
    /// routes through the external `ark-gb` crate (Singular-class
    /// performance); `ElimTerm` keeps the in-tree implementation.
    pub fn buchberger_and_reduce(self) -> Self {
        let reduced = T::compute_reduced_gb(self.num_vars, self.basis);
        Self::new(self.num_vars, reduced)
    }

    /// Compute a Gröbner basis. Same dispatch as
    /// [`Self::buchberger_and_reduce`]; the result is fully reduced
    /// (`buchberger_and_reduce`'s output is also a Gröbner basis, so
    /// returning it from `buchberger` satisfies the weaker contract).
    pub fn buchberger(&self) -> Self {
        let reduced = T::compute_reduced_gb(self.num_vars, self.basis.clone());
        Self::new(self.num_vars, reduced)
    }

    /// Reduce an existing Gröbner basis to its minimal, reduced form.
    /// Dispatches via [`Monomial::compute_reduced_gb`]: idempotent on
    /// an already-reduced basis.
    pub fn reduce_groebner_basis(&mut self) {
        let basis = std::mem::take(&mut self.basis);
        self.basis = T::compute_reduced_gb(self.num_vars, basis);
    }
}

/// In-tree Buchberger + reduction. Test-only fixture used by
/// `speedup_bench` to A/B against the ark-gb path; not called from
/// production code.
#[cfg(test)]
pub(crate) fn legacy_compute_reduced_gb<F: Field, T: Monomial>(
    num_vars: usize,
    basis: Vec<SparsePolynomial<F, T>>,
) -> Vec<SparsePolynomial<F, T>> {
    let mut g = GroebnerBasis::new(num_vars, basis).legacy_buchberger();
    g.legacy_reduce_groebner_basis();
    g.basis
}

impl<F: Field, T: Monomial> fmt::Display for GroebnerBasis<F, T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for p in self.iter() {
            writeln!(f, "\t{} == 0", p)?;
        }
        Ok(())
    }
}
