use ark_ff::Field;
use std::collections::{HashSet, VecDeque};
use std::fmt;
use std::ops::Index;

use crate::PRef;
use crate::analyses::groebner::{Monomial, SparsePolynomial};
use log::debug;
use rayon::prelude::*;
use share::Set;

#[cfg(test)]
use ark_ff::AdditiveGroup;

/// A struct representing a Gröbner basis.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GroebnerBasis<F: Field, T: Monomial> {
    pub basis: Vec<SparsePolynomial<F, T>>,
    pub num_vars: usize,
}

impl<F: Field, T: Monomial> Index<usize> for GroebnerBasis<F, T> {
    type Output = SparsePolynomial<F, T>;

    fn index(&self, index: usize) -> &Self::Output {
        &self.basis[index]
    }
}

impl<F: Field, T: Monomial> IntoIterator for GroebnerBasis<F, T> {
    type Item = SparsePolynomial<F, T>;
    type IntoIter = std::vec::IntoIter<SparsePolynomial<F, T>>;

    fn into_iter(self) -> Self::IntoIter {
        self.basis.into_iter()
    }
}

impl<F: Field, T: Monomial> GroebnerBasis<F, T> {
    pub fn new(num_vars: usize, basis: Vec<SparsePolynomial<F, T>>) -> Self {
        Self { basis, num_vars }
    }

    pub fn empty(num_vars: usize) -> Self {
        Self {
            basis: Vec::new(),
            num_vars,
        }
    }

    pub fn contains_poly(&self, poly: &SparsePolynomial<F, T>) -> bool {
        let poly = poly.clone();
        let rem = self.reduce(poly);
        rem.is_zero() // If the reduction is zero, poly is in the ideal generated by the basis
    }

    pub fn contains(&self, other: &Self) -> bool {
        other.basis.iter().all(|p| self.contains_poly(p))
    }

    pub fn is_empty(&self) -> bool {
        self.basis.is_empty()
    }

    pub fn len(&self) -> usize {
        self.basis.len()
    }

    pub fn iter(&self) -> impl Iterator<Item = &SparsePolynomial<F, T>> {
        self.basis.iter()
    }

    pub fn push(&mut self, poly: SparsePolynomial<F, T>) {
        self.basis.push(poly);
    }

    pub fn eliminate_var<FF: Fn(&PRef) -> bool>(&mut self, f: &FF) {
        self.basis.retain(|p| p.vars().find(|v| f(v)).is_none());
    }

    pub fn eliminate_monomial<FF: Fn(&T) -> bool>(&mut self, f: &FF) {
        self.basis.retain(|p| p.terms.iter().any(|(t, _)| !f(t)));
    }

    pub fn iter_mut<'a>(&'a mut self) -> impl Iterator<Item = &'a mut SparsePolynomial<F, T>> {
        self.basis.iter_mut()
    }

    pub fn vars(&self) -> Set<PRef> {
        self.basis
            .iter()
            .flat_map(|p| p.vars().into_iter())
            .collect()
    }

    /// Reduces polynomial `p` with respect to the basis `G`.
    /// Returns the remainder `r` such that `p = sum(q_i * g_i) + r`, and no term in `r`
    /// is divisible by the leading term of any `g_i` in `G`.
    /// Assumes `G` does not contain the zero polynomial.
    pub fn reduce(&self, mut p: SparsePolynomial<F, T>) -> SparsePolynomial<F, T> {
        let mut remainder = SparsePolynomial::zero();

        // The basis against which we reduce. Filter out zeros once.
        let reducers: Vec<_> = self.basis.iter().filter(|poly| !poly.is_zero()).collect();

        // While p is not zero
        while let Some((p_lc, p_lt)) = p.leading_term() {
            let found_divisor = reducers.par_iter().find_any(|g| {
                if let Some((_g_lc, g_lt)) = g.leading_term() {
                    p_lt.is_divided(&g_lt)
                } else {
                    false
                }
            });

            if let Some(g) = found_divisor {
                let (g_lc, g_lt) = g.leading_term().unwrap();
                let multiplier_term =
                    (p_lt / g_lt).expect("Division should succeed if is_divided is true");
                let multiplier_scalar = p_lc
                    * g_lc
                        .inverse()
                        .expect("Leading coefficient must be invertible");
                let to_subtract = g.mul_by_term_and_scalar(multiplier_scalar, &multiplier_term);
                p -= to_subtract;
            } else {
                // No division occurred, move LT(p) to the remainder.
                let (lt, lc) = p.terms.pop_first().unwrap(); // BTreeMap specific method
                remainder.terms.insert(&lt, &lc); // Add to remainder
            }
        }

        remainder
    }

    /// Group-parallel pair selection
    fn pairs_select(&self, pairs: &mut VecDeque<(usize, usize)>) -> Vec<(usize, usize)> {
        let num_threads = std::thread::available_parallelism()
            .map(|n| n.get())
            .unwrap_or(1)
            .saturating_sub(1)
            .max(2);

        let mut selected = Vec::new();
        for _ in 0..num_threads {
            if let Some((i, j)) = pairs.pop_front() {
                if i < self.len() && j < self.len() {
                    selected.push((i, j));
                }
            } else {
                break;
            }
        }
        selected
    }

    /*
    fn pairs_select_single(&self, pairs: &mut VecDeque<(usize, usize)>) -> Vec<(usize, usize)> {
        if let Some((i, j)) = pairs.pop_front() {
            if i < self.len() && j < self.len() {
                vec![(i, j)]
            } else {
                vec![]
            }
        } else {
            vec![]
        }
    }
    */

    /// Eventually we want to implement F4 pair reduction
    fn pairs_reduce(&self, _ps: &mut Vec<(usize, usize)>) {}

    /// Computes a Gröbner basis for the ideal generated by `F` using Buchberger's algorithm.
    /// `F` is the initial set of generator polynomials.
    pub fn buchberger(&self) -> Self {
        if self.basis.is_empty() {
            return Self::empty(self.num_vars);
        }

        // Initialize with non-zero polynomials
        let basis_nonzero = self
            .basis
            .iter()
            .filter(|p| !p.is_zero())
            .cloned()
            .collect();

        let mut g: Self = Self::new(self.num_vars, basis_nonzero);

        // Initialize the set of critical pairs (indices into G)
        let mut pairs: VecDeque<(usize, usize)> = VecDeque::new();
        let mut seen = HashSet::new();

        for i in 0..g.len() {
            for j in (i + 1)..g.len() {
                pairs.push_back((i, j));
            }
        }

        while pairs.len() > 0 {
            let mut ps = g.pairs_select(&mut pairs);
            // F4 symbolic reduction
            g.pairs_reduce(&mut ps);

            // Add pairs to seen set
            seen.extend(ps.iter().map(|(i, j)| (*i, *j)));

            let reduced_ps: Vec<SparsePolynomial<F, T>> = ps
                .par_iter()
                .filter_map(|&(i, j)| {
                    // Ensure indices are still valid (G might grow)
                    if i >= g.len() || j >= g.len() {
                        return None;
                    }

                    let g_i = &g[i];
                    let g_j = &g[j];

                    debug!("Processing pair ({}, {})", i, j); // Debug output

                    // Compute S-polynomial
                    let s_poly = g_i.s_poly(g_j);

                    if s_poly.is_zero() {
                        // S-polynomial reduced to zero immediately
                        debug!("  S(G[{}], G[{}]) = 0", i, j);
                        return None;
                    }

                    // Reduce the S-polynomial with respect to the current basis G
                    let s_reduced = g.reduce(s_poly);

                    // If the reduced S-polynomial is not zero, return it
                    if !s_reduced.is_zero() {
                        debug!("  S(G[{}], G[{}]) reduces to non-zero polynomial.", i, j);
                        return Some(s_reduced);
                    } else {
                        debug!("  S(G[{}], G[{}]) reduces to 0", i, j);
                        return None;
                    }
                })
                .collect();

            // Add new polynomials and generate pairs
            for s_reduced in reduced_ps {
                let k = g.len(); // Index of the polynomial we're about to add
                g.push(s_reduced);

                // Add new critical pairs involving the new polynomial h (index k)
                // with all existing polynomials in G (indices 0 to k-1)
                for l in 0..k {
                    if !Self::skip_pair(l, k, &g, &seen) {
                        pairs.push_back((l, k));
                    }
                }
            }
        }

        // Return the computed Gröbner basis (not necessarily minimal/reduced yet)
        g
    }

    /// Buchberger's criteria (https://www.andrew.cmu.edu/course/15-355/lectures/lecture11.pdf)
    fn skip_pair(
        l: usize,
        k: usize,
        g: &GroebnerBasis<F, T>,
        seen: &HashSet<(usize, usize)>,
    ) -> bool {
        // Buchberger's first criterion: skip pairs (l, k) if their leading monomials are coprime (LCM is product)
        let lt_l = g[l].leading_term().map(|(_, m)| m);
        let lt_k = g[k].leading_term().map(|(_, m)| m);
        if let (Some(ml), Some(mk)) = (lt_l, lt_k) {
            // Buchberger's first criterion: skip pairs (l, k) if their leading monomials are coprime (LCM is product)
            if ml.is_coprime(&mk) {
                return true;
            }

            // Buchberger's second criterion: skip pairs (l, k) if there exists an [i] such that LCM(LT(l), LT(k)) is a multiple of LT(i)
            // and (l, i) and (i, k) have been seen before
            return (0..g.len()).into_par_iter().any(|i| {
                if let Some(lt_i) = g[i].leading_term().map(|(_, m)| m) {
                    if ml.lcm(&mk).is_divided(&lt_i)
                        && seen.contains(&(l, i))
                        && seen.contains(&(i, k))
                    {
                        return true;
                    }
                }
                false
            });
        }
        false
    }

    /// Reduces a computed Gröbner basis `G` to a minimal, reduced Gröbner basis.
    /// 1. Makes all polynomials monic.
    /// 2. Removes redundant polynomials (whose LT is divisible by another's LT).
    /// 3. Reduces each polynomial against the others.
    pub fn reduce_groebner_basis(&mut self) {
        // --- Step 0: Calculate the number of variables ---
        let num_vars = self.num_vars;

        // --- Step 1: Make polynomials monic & initial cleanup ---
        let mut g_monic = GroebnerBasis::empty(num_vars);
        for p in self.iter() {
            if p.is_zero() {
                continue;
            } // Remove zero polynomials

            if let Some((lc, _)) = p.leading_term() {
                let lc_inv = lc
                    .inverse()
                    .expect("Leading coefficient must be invertible in a Field for non-zero poly");

                // Multiply the entire polynomial by lc_inv
                let mut monic_p = SparsePolynomial::zero(); // Start fresh
                for (term, coeff) in p.terms.iter() {
                    monic_p.terms.insert(term, &(*coeff * lc_inv));
                }

                // Ensure it's still not zero after making monic (unlikely but possible with weird fields)
                if !monic_p.is_zero() {
                    g_monic.push(monic_p);
                }
            }
            // else: p was zero, already skipped
        }
        *self = g_monic; // Replace G with the monic version

        // Sort by leading term order (important for the next step)
        // This assumes the Ord trait on Monomial defines the term order used.
        self.basis.sort_unstable_by(|p1, p2| {
            let lt1 = p1.leading_term().map(|(_, t)| t);
            let lt2 = p2.leading_term().map(|(_, t)| t);
            lt1.cmp(&lt2) // Compare leading terms
        });

        // --- Step 2: Remove polynomials whose leading term is divisible by another's LT ---
        // This step creates a "minimal" basis (but not yet "reduced")
        let mut g_minimal = GroebnerBasis::empty(num_vars);
        let mut discarded = vec![false; self.len()];

        for i in 0..self.len() {
            if discarded[i] {
                continue;
            }
            let lt_i = self[i].leading_term().unwrap().1; // Safe unwrap: non-zero polys

            for j in (i + 1)..self.len() {
                if discarded[j] {
                    continue;
                }
                let lt_j = self[j].leading_term().unwrap().1;

                // If LT(j) is_divided LT(i), mark j for removal (since G is sorted by LT)
                // Note: If LT(i) == LT(j), this should theoretically not happen if basis elements are distinct
                // and monic, but we handle it by discarding j.
                if lt_j.is_divided(&lt_i) {
                    discarded[j] = true;
                }
                // We don't need to check if LT(i) is_divided LT(j) because G is sorted by LT.
            }
        }

        // Collect non-discarded polynomials
        for i in 0..self.len() {
            if !discarded[i] {
                g_minimal.push(self[i].clone()); // Clone necessary as we modify below
            }
        }
        *self = g_minimal; // Update G

        // --- Step 3: Inter-reduce the basis (Full Reduction) ---
        // For each g in G, reduce it by G \ {g}.
        let mut g_reduced = GroebnerBasis::new(num_vars, Vec::with_capacity(self.len()));
        for i in 0..self.len() {
            let current_g = self[i].clone();

            // Create basis for reduction: G excluding current_g
            let mut reduction_basis = GroebnerBasis::empty(num_vars);
            for j in 0..self.len() {
                if i != j {
                    reduction_basis.push(self[j].clone());
                }
            }

            // Reduce current_g by the rest of the basis
            let reduced_g = reduction_basis.reduce(current_g);

            // Add the fully reduced polynomial (it should still be monic and non-zero
            // unless the basis was {c} -> {1} and reduction makes it 0, which we filter)
            if !reduced_g.is_zero() {
                g_reduced.push(reduced_g);
            }
        }

        // Final sort (optional, but good practice)
        g_reduced.basis.sort_unstable_by(|p1, p2| {
            let lt1 = p1.leading_term().map(|(_, t)| t);
            let lt2 = p2.leading_term().map(|(_, t)| t);
            lt1.cmp(&lt2)
        });

        *self = g_reduced;
    }

    pub fn buchberger_and_reduce(self) -> Self {
        let mut g = self.buchberger();
        g.reduce_groebner_basis();
        g
    }
}

impl<F: Field, T: Monomial> fmt::Display for GroebnerBasis<F, T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for p in self.iter() {
            write!(f, "\t{} == 0\n", p)?;
        }
        Ok(())
    }
}

// --- Example Usage ---
#[cfg(test)]
use crate::analyses::groebner::{ElimTerm, GrevLexTerm};
#[cfg(test)]
use ark_bls12_381::Fr as Fp; // Using a prime field
#[cfg(test)]
use ark_ff::One;
#[cfg(test)]
use backend::ATyp;
#[cfg(test)]
use lang::id::Vid;
#[cfg(test)]
use lang::typ::{Distribution, Qualifier};
#[cfg(test)]
use petgraph::graph::NodeIndex;
#[cfg(test)]
use share::assert_deq;

#[cfg(test)]
fn elim_var<'a>(name: &'a str) -> PRef {
    PRef::from_var(
        Vid::new(name),
        NodeIndex::new(0),
        ATyp::scalar(),
        0,
        Qualifier::Private,
        Distribution::Uniform,
    )
}

#[cfg(test)]
fn noelim_var<'a>(name: &'a str) -> PRef {
    PRef::from_var(
        Vid::new(name),
        NodeIndex::new(0),
        ATyp::scalar(),
        0,
        Qualifier::Public,
        Distribution::Nonuniform,
    )
}

#[cfg(test)]
fn elim_term(vars: Vec<(&PRef, usize)>) -> ElimTerm {
    ElimTerm::from(
        vars.into_iter()
            .map(|(v, i)| (v.clone(), i))
            .collect::<Vec<_>>(),
    )
}

#[cfg(test)]
fn grevlex_term(vars: Vec<(&PRef, usize)>) -> GrevLexTerm {
    GrevLexTerm::from(
        vars.into_iter()
            .map(|(v, i)| (v.clone(), i))
            .collect::<Vec<_>>(),
    )
}

#[test]
fn test_term_ops() {
    let x = elim_var("x");
    let y = elim_var("y");
    let z = elim_var("z");

    let t1 = elim_term(vec![(&x, 2), (&y, 3)]); // x^2 y^3 (vars 0, 1)
    let t2 = elim_term(vec![(&x, 1), (&y, 2)]); // x y^2
    let t3 = elim_term(vec![(&z, 1)]); // z

    // term_mult
    let t1_t2_mult = &t1 * &t2; // x^3 y^5
    assert_deq!(t1_t2_mult, elim_term(vec![(&x, 3), (&y, 5)]));

    let t1_t3_mult = &t1 * &t3; // x^2 y^3 z
    assert_deq!(t1_t3_mult, elim_term(vec![(&x, 2), (&y, 3), (&z, 1)]));

    // term_is_divided
    assert!(t1.is_divided(&t2));
    assert!(!t2.is_divided(&t1));
    assert!(!t1.is_divided(&t3));

    // term_div
    let t1_div_t2 = (&t1 / &t2).unwrap(); // x y
    assert_deq!(t1_div_t2, elim_term(vec![(&x, 1), (&y, 1)]));
    assert!((&t2 / &t1).is_none());

    // lcm_terms
    let lcm_t1_t2 = t1.lcm(&t2); // x^2 y^3
    assert_deq!(lcm_t1_t2, t1);

    let t4 = elim_term(vec![(&x, 3), (&y, 1)]); // x^3 y
    let lcm_t1_t4 = t1.lcm(&t4); // x^3 y^3
    assert_deq!(lcm_t1_t4, elim_term(vec![(&x, 3), (&y, 3)]));
}

#[test]
fn test_s_polynomial() {
    let x = elim_var("x");
    let y = elim_var("y");

    let f: SparsePolynomial<Fp, ElimTerm> = elim_sparse_poly(vec![
        (Fp::one(), vec![(&x, 2)]),  // x^2
        (-Fp::one(), vec![(&y, 1)]), // -y
    ]); // x^2 - y

    let g = elim_sparse_poly(vec![
        (Fp::one(), vec![(&x, 1), (&y, 1)]), // xy
        (Fp::one(), vec![]),                 // +1
    ]); // xy + 1

    // LT(f) = x^2, LT(g) = xy
    // lcm(LT(f), LT(g)) = x^2 y
    // multiplier_f = (x^2 y / x^2) * (1/-1) = y
    // multiplier_g = (x^2 y / xy) * (1/1) = x
    // S(f, g) = y * (x^2 - y) - x * (xy + 1)
    //         = x^2 y - y^2 - x^2 y - x
    //         = -y^2 - x
    // Leading term (lexicographic, y < x): -x

    let s = f.s_poly(&g);

    let expected_s = elim_sparse_poly(vec![
        (-Fp::one(), vec![(&x, 1)]), // -x
        (-Fp::one(), vec![(&y, 2)]), // -y^2
    ]);

    assert_deq!(s, expected_s);
}

#[cfg(test)]
use crate::analyses::groebner::sparsepoly::{elim_sparse_poly, grevlex_sparse_poly};
#[cfg(test)]
use core::cmp::Ordering;

#[test]
fn test_grevlex_ordering() {
    let x1 = elim_var("x1");
    let x2 = elim_var("x2");
    let x3 = elim_var("x3");

    let f1 = grevlex_term(vec![(&x1, 2)]); // x1^2
    let f2 = grevlex_term(vec![(&x1, 1), (&x2, 1)]); // x1 x2
    let f4 = grevlex_term(vec![(&x2, 2)]); // x2^2
    let f3 = grevlex_term(vec![(&x1, 1), (&x3, 1)]); // x1 x3
    let f5 = grevlex_term(vec![(&x2, 1), (&x3, 1)]); // x2 x3
    let f6 = grevlex_term(vec![(&x3, 2)]); // x3^2
    let f7 = grevlex_term(vec![]); // 1

    // Textbook degrevlex with variable ordering x1 > x2 > x3 (i.e. x3 is the
    // "rightmost" / smallest variable). Largest monomial first, then tied on
    // degree => smallest exponent on x3, then x2. Leading (= largest) sorts
    // FIRST under this `Ord` (see `leading_term` / `BTreeMap::first`):
    //   x1^2  >  x1*x2  >  x2^2  >  x1*x3  >  x2*x3  >  x3^2  >  1
    let mut terms = vec![&f3, &f4, &f1, &f5, &f6, &f2, &f7]
        .into_iter()
        .map(|t| t.clone())
        .collect::<Vec<_>>();

    terms.sort_unstable_by(|a, b| a.cmp(b));
    assert_eq!(terms, vec![f1, f2, f4, f3, f5, f6, f7]);
}

/// Textbook degrevlex counterexamples that caught the old left-to-right
/// tie-breaker. With PRef ordering x1 < x2 < x3, "rightmost" = x3.
/// Under "leading = Ord::Less" convention: the larger monomial returns `Less`.
#[test]
fn test_grevlex_degrevlex_counterexamples() {
    let x1 = elim_var("x1");
    let x2 = elim_var("x2");
    let x3 = elim_var("x3");

    // x1^2 vs x2*x3 (both deg 2). Rightmost differing var is x3: x1^2 has
    // exp 0, x2*x3 has exp 1. Larger exp on x3 => smaller monomial; so
    // x1^2 > x2*x3, i.e. x1^2 is leading => Ord::Less.
    let a = grevlex_term(vec![(&x1, 2)]);
    let b = grevlex_term(vec![(&x2, 1), (&x3, 1)]);
    assert_eq!(a.cmp(&b), Ordering::Less, "x1^2 > x2*x3 in degrevlex");

    // x1^2 vs x1*x2. Rightmost differing is x2: x1^2 has 0, x1*x2 has 1.
    // x1^2 leading => Ord::Less.
    let a = grevlex_term(vec![(&x1, 2)]);
    let b = grevlex_term(vec![(&x1, 1), (&x2, 1)]);
    assert_eq!(a.cmp(&b), Ordering::Less, "x1^2 > x1*x2 in degrevlex");

    // x2^2 vs x1*x3. Both deg 2. Rightmost differing is x3: x2^2 has 0,
    // x1*x3 has 1. x2^2 leading => Ord::Less. (This specifically distinguishes
    // degrevlex from graded-lex, which would say x1*x3 > x2^2.)
    let a = grevlex_term(vec![(&x2, 2)]);
    let b = grevlex_term(vec![(&x1, 1), (&x3, 1)]);
    assert_eq!(a.cmp(&b), Ordering::Less, "x2^2 > x1*x3 in degrevlex");

    // Degree dominates: x1 (deg 1) < x3^2 (deg 2) in "leading" sense means
    // x3^2 leading => x3^2.cmp(x1) = Less.
    let a = grevlex_term(vec![(&x3, 2)]);
    let b = grevlex_term(vec![(&x1, 1)]);
    assert_eq!(a.cmp(&b), Ordering::Less, "higher degree is leading");
}

// A simple test case for a linear system, this should work as Gaussian elimination
#[test]
fn test_linear() {
    let a = elim_var("a");
    let b = elim_var("b");
    let s1 = elim_var("s1");
    let s2 = elim_var("s2");
    let r = elim_var("r");
    let num_vars = 5;

    // s1 + r - a
    let f1: SparsePolynomial<Fp, GrevLexTerm> = grevlex_sparse_poly(vec![
        (-Fp::one(), vec![(&a, 1)]), // -a
        (Fp::one(), vec![(&s1, 1)]), // s1
        (Fp::one(), vec![(&r, 1)]),  // r
    ]);

    // s2 + r - b
    let f2 = grevlex_sparse_poly(vec![
        (-Fp::one(), vec![(&b, 1)]), // -b
        (Fp::one(), vec![(&s2, 1)]), // s2
        (Fp::one(), vec![(&r, 1)]),  // r
    ]);

    let initial_basis = GroebnerBasis::new(num_vars, vec![f1, f2]);
    debug!("Ideal:");
    for p in initial_basis.iter() {
        debug!("{}", p);
    }

    let groebner_basis = initial_basis.buchberger();
    debug!("Computed Gröbner Basis:");
    for p in groebner_basis.iter() {
        debug!("{}", p);
    }
}

// A simple test case from the Maplesoft docs for Groebner LexDeg bases
#[test]
fn test_maple() {
    let t = elim_var("t");
    let x = noelim_var("x");
    let y = noelim_var("y");
    let num_vars = 3;

    // Ideal
    let f1: SparsePolynomial<Fp, ElimTerm> = elim_sparse_poly(vec![
        (Fp::one(), vec![(&t, 2), (&y, 1)]),  // t^2 y
        (-Fp::one().double(), vec![(&t, 1)]), // -2t
        (Fp::one(), vec![(&y, 1)]),           // +y
    ]);

    let f2 = elim_sparse_poly(vec![
        (Fp::one(), vec![(&t, 2), (&x, 1)]), // t^2 x
        (Fp::one(), vec![(&t, 2)]),          // t^2
        (Fp::one(), vec![(&x, 1)]),          // x
        (-Fp::one(), vec![]),                // -1
    ]);

    let initial_basis = GroebnerBasis::new(num_vars, vec![f1, f2]);
    let groebner_basis = initial_basis.buchberger_and_reduce();

    // The correct result should be:
    // t*x + t - y
    // t*y + x - 1
    // x^2 + y^2 - 1
    let g1 = elim_sparse_poly(vec![
        (Fp::one(), vec![(&t, 1), (&x, 1)]), // tx
        (Fp::one(), vec![(&t, 1)]),          // t
        (-Fp::one(), vec![(&y, 1)]),         // -y
    ]);

    let g2 = elim_sparse_poly(vec![
        (Fp::one(), vec![(&t, 1), (&y, 1)]), // ty
        (Fp::one(), vec![(&x, 1)]),          // x
        (-Fp::one(), vec![]),                // -1
    ]);

    let g3 = elim_sparse_poly(vec![
        (Fp::one(), vec![(&x, 2)]), // x^2
        (Fp::one(), vec![(&y, 2)]), // y^2
        (-Fp::one(), vec![]),       // -1
    ]);

    assert_eq!(
        groebner_basis,
        GroebnerBasis::new(num_vars, vec![g1, g2, g3])
    );
}
