use crate::PRef;
use crate::analyses::groebner::sparsepoly::SparsePolynomial;
use ark_ff::Field;
use core::cmp::Ordering;
use core::ops::{Div, Mul, MulAssign};
use share::Ctx;
use std::fmt;
use std::fmt::Debug;

/// A monomial trait that represents a term in a polynomial.
pub trait Monomial:
    Clone
    + PartialEq
    + Eq
    + Default
    + Send
    + Sync
    + fmt::Display
    + MulAssign
    + Mul<Output = Self>
    + Div<Output = Option<Self>>
    + From<Vec<(PRef, usize)>>
    + Ord
{
    fn vars(&self) -> Vec<PRef>;
    fn powers(&self) -> Vec<usize>;
    fn degree(&self) -> usize {
        self.powers().iter().sum()
    }
    fn is_constant(&self) -> bool {
        self.vars().is_empty()
    }
    fn remap_vars(&self, f: &dyn Fn(&PRef) -> PRef) -> Self {
        let pairs: Vec<(PRef, usize)> = self
            .vars()
            .iter()
            .zip(self.powers().iter())
            .map(|(v, &p)| (f(v), p))
            .collect();
        Self::from(pairs)
    }
    fn evaluate<F: Field>(&self, p: &Ctx<PRef, F>) -> F;

    fn is_divided(&self, other: &Self) -> bool;

    fn is_coprime(&self, other: &Self) -> bool {
        self.gcd(other).is_constant()
    }
    fn lcm(&self, other: &Self) -> Self;
    fn gcd(&self, other: &Self) -> Self;

    /// Compute the reduced Gröbner basis of the ideal generated by `input`.
    ///
    /// This is the Groebner backend hook for the supported term orderings.
    /// `GrevLexTerm` routes through the ark-gb grevlex adapter, and
    /// `ElimTerm` routes through the ark-gb elim adapter.
    ///
    /// W is the packed monomial width (8 or 16). Caller must ensure W is
    /// appropriate for the problem size.
    fn compute_reduced_gb<F: Field, const W: usize>(
        num_vars: usize,
        input: Vec<SparsePolynomial<F, Self>>,
    ) -> Vec<SparsePolynomial<F, Self>>
    where
        Self: Sized;
}

#[derive(Clone, PartialEq, Eq, PartialOrd, Debug)]
pub struct MonoTerm(Ctx<PRef, usize>); // (var index, power)

/// Strategy for deciding which variables to eliminate in a block-elimination order.
///
/// Implementations are zero-sized marker types that carry the `eliminate_var`
/// predicate as an associated function, allowing `ElimTerm<E>` to share all
/// boilerplate (arithmetic, `Monomial` impl, `Ord`) across strategies.
pub trait ElimStrategy: Sized + Send + Sync {
    /// Returns `true` if `v` belongs to the elimination block (compared first
    /// in the two-level block-elimination monomial order).
    fn eliminate_var(v: &PRef) -> bool;
}

/// A monomial term with grevlex ordering
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct GrevLexTerm(MonoTerm);

/// A monomial term with block-elimination ordering, parameterized by the
/// elimination strategy `E`.
///
/// The `Ord` implementation uses a two-level block order: first compare the
/// elimination block (variables for which `E::eliminate_var` returns true)
/// via grevlex, then the kept block via grevlex.
pub struct ElimMono<E: ElimStrategy>(MonoTerm, std::marker::PhantomData<E>);

impl<E: ElimStrategy> Clone for ElimMono<E> {
    fn clone(&self) -> Self {
        ElimMono(self.0.clone(), std::marker::PhantomData)
    }
}

impl<E: ElimStrategy> PartialEq for ElimMono<E> {
    fn eq(&self, other: &Self) -> bool {
        self.0 == other.0
    }
}

impl<E: ElimStrategy> Eq for ElimMono<E> {}

impl<E: ElimStrategy> Debug for ElimMono<E> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("ElimMono").field(&self.0).finish()
    }
}

impl From<MonoTerm> for GrevLexTerm {
    fn from(t: MonoTerm) -> Self {
        GrevLexTerm(t)
    }
}

impl<E: ElimStrategy> From<MonoTerm> for ElimMono<E> {
    fn from(t: MonoTerm) -> Self {
        ElimMono(t, std::marker::PhantomData)
    }
}

impl MonoTerm {
    fn vars(&self) -> Vec<PRef> {
        self.0.keys().into_iter().collect()
    }
    fn powers(&self) -> Vec<usize> {
        self.0.values().into_iter().collect()
    }
    fn degree(&self) -> usize {
        self.powers().iter().sum()
    }
    fn is_constant(&self) -> bool {
        self.0.is_empty() // Empty vec means the term is 1 (constant)
    }

    fn evaluate<F: Field>(&self, p: &Ctx<PRef, F>) -> F {
        let mut result = F::one();
        for (var, power) in self.0.iter() {
            // Missing variables contribute multiplicative identity.
            if let Some(value) = p.get(var) {
                for _ in 0..*power {
                    result *= value;
                }
            }
        }
        result
    }
    fn is_divided(&self, other: &Self) -> bool {
        for (var, power2) in other.0.iter() {
            match self.0.get(var) {
                Some(power1) => {
                    if power1 < power2 {
                        return false;
                    }
                }
                None => return false, // other has a variable self doesn't have
            }
        }
        true // All variables in other are in self with sufficient power
    }

    fn lcm(&self, other: &Self) -> Self {
        let mut lcm_powers: Vec<(PRef, usize)> =
            self.0.iter().map(|(v, p)| (v.clone(), *p)).collect();
        for (var, power2) in other.0.iter() {
            match lcm_powers.iter_mut().find(|(v, _)| v == var) {
                Some((_, power1)) => *power1 = (*power1).max(*power2),
                None => lcm_powers.push((var.clone(), *power2)),
            }
        }
        MonoTerm(lcm_powers.into_iter().collect())
    }

    fn gcd(&self, other: &Self) -> Self {
        let mut gcd_powers: Vec<(PRef, usize)> = Vec::new();
        for (var1, power1) in self.0.iter() {
            if let Some((_, power2)) = other.0.iter().find(|(v, _p)| v == &var1) {
                let min_power = (*power1).min(*power2);
                if min_power > 0 {
                    gcd_powers.push((var1.clone(), min_power));
                }
            }
        }
        MonoTerm(gcd_powers.into_iter().collect())
    }

    fn div(self, other: Self) -> Option<Self> {
        if !self.is_divided(&other) {
            return None;
        }

        let mut powers1 = self
            .0
            .iter()
            .map(|(v, p)| (v.clone(), *p))
            .collect::<Vec<_>>();
        for (var, power2) in other.0.iter() {
            // We know var is in powers1 with sufficient power because term_is_divided was true
            if let Some(power1) = powers1.iter_mut().find(|(v, _)| v == var) {
                power1.1 -= power2;
            }
        }

        Some(MonoTerm(
            powers1.into_iter().filter(|(_, p)| *p > 0).collect(),
        ))
    }

    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.is_constant() {
            write!(f, "1")
        } else {
            let mut terms: Vec<String> = Vec::new();
            for (var, power) in self.0.iter() {
                if *power == 1 {
                    terms.push(format!("{}", var));
                } else if *power > 0 {
                    terms.push(format!("{}^{}", var, power));
                }
            }
            write!(f, "{}", terms.join("*"))
        }
    }

    // Graded reverse-lexicographic order (degrevlex).
    //
    // Convention in this codebase: the BTreeMap keyed by `Ord` yields the
    // *leading* term via `BTreeMap::first` (see `SparsePolynomial::leading_term`),
    // so the Ord we return treats "leading" (the mathematically largest
    // monomial) as `Ordering::Less` ("first in the map").
    //
    // Textbook degrevlex rule for same-degree monomials:
    //     at the rightmost variable where exponents differ, the monomial with
    //     the SMALLER exponent is the LARGER (= leading) monomial.
    //
    // Variable ordering: textbook convention is that the *leftmost*-named
    // variable is the "largest". In this codebase `PRef` is Ord by underlying
    // `Vid` (alphabetical), so PRef-smallest = textbook-largest variable, and
    // PRef-LARGEST = textbook-RIGHTMOST. We therefore walk both BTreeMaps in
    // reverse (descending PRef) to visit the rightmost coordinate first.
    //
    // Concretely, for vars a < b < c (PRef order), "rightmost" = c:
    //   `a^2 > b*c` because `b*c` has a larger exponent (1) than `a^2` (0) on
    //   the rightmost var c; `a^2` is leading, so `a^2.cmp(&b*c) = Less`.
    fn grevlex(&self, other: &Self) -> Ordering {
        // 1. Total degree first — higher degree is leading (Ord::Less).
        match self.degree().cmp(&other.degree()) {
            Ordering::Equal => {}
            order => return order.reverse(),
        };

        // 2. Merge-walk both maps from largest PRef to smallest, treating
        //    absent keys as exponent 0. `Ctx::iter()` is DoubleEndedIterator.
        let mut a = self.0.iter().rev().peekable();
        let mut b = other.0.iter().rev().peekable();
        loop {
            match (a.peek(), b.peek()) {
                (None, None) => return Ordering::Equal,
                (Some(_), None) => return Ordering::Greater,
                (None, Some(_)) => return Ordering::Less,
                (Some(&(va, _pa)), Some(&(vb, _pb))) => match va.cmp(vb) {
                    Ordering::Greater => return Ordering::Greater,
                    Ordering::Less => return Ordering::Less,
                    Ordering::Equal => {
                        let (_, pa) = a.next().unwrap();
                        let (_, pb) = b.next().unwrap();
                        match pa.cmp(pb) {
                            Ordering::Equal => continue,
                            order => return order,
                        }
                    }
                },
            }
        }
    }

    fn iter(&self) -> impl Iterator<Item = (&PRef, &usize)> {
        self.0.iter()
    }
}

/// Constructors for GrevLexTerm
impl GrevLexTerm {
    pub fn new(vars: Ctx<PRef, usize>) -> Self {
        GrevLexTerm(MonoTerm(vars))
    }

    pub fn iter(&self) -> impl Iterator<Item = (&PRef, &usize)> {
        self.0.iter()
    }
}

/// Constructors for ElimMono<E>
impl<E: ElimStrategy> ElimMono<E> {
    pub fn new(vars: Ctx<PRef, usize>) -> Self {
        ElimMono(MonoTerm(vars), std::marker::PhantomData)
    }

    pub fn eliminate(&self) -> bool {
        self.0.iter().any(|(v, _)| E::eliminate_var(v))
    }

    pub fn iter(&self) -> impl Iterator<Item = (&PRef, &usize)> {
        self.0.iter()
    }

    /// Borrow the underlying `MonoTerm` (variable → exponent map).
    pub(crate) fn as_mono_term(&self) -> &MonoTerm {
        &self.0
    }
}

/// Default constructors for Monomials
impl<E: ElimStrategy> Default for ElimMono<E> {
    fn default() -> Self {
        ElimMono(MonoTerm(Ctx::new()), std::marker::PhantomData)
    }
}

impl Default for GrevLexTerm {
    fn default() -> Self {
        GrevLexTerm(MonoTerm(Ctx::new()))
    }
}

/// Multiplies two terms in place. (var, power) pairs are combined by adding powers
/// for common variables.
#[allow(clippy::suspicious_op_assign_impl)]
impl<E: ElimStrategy> MulAssign for ElimMono<E> {
    #[allow(clippy::suspicious_op_assign_impl)]
    fn mul_assign(&mut self, other: Self) {
        for (var, power) in other.0.iter() {
            *self.0.0.entry(var.clone()).or_insert(0) += power;
        }
    }
}

#[allow(clippy::suspicious_op_assign_impl)]
impl MulAssign for GrevLexTerm {
    #[allow(clippy::suspicious_op_assign_impl)]
    fn mul_assign(&mut self, other: Self) {
        for (var, power) in other.0.iter() {
            *self.0.0.entry(var.clone()).or_insert(0) += power;
        }
    }
}

/// Multiplies two terms. (var, power) pairs are combined by adding powers
impl<E: ElimStrategy> Mul for ElimMono<E> {
    type Output = Self;

    fn mul(self, other: Self) -> Self {
        let mut result = self.clone();
        result *= other;
        result
    }
}

impl Mul for GrevLexTerm {
    type Output = Self;

    fn mul(self, other: Self) -> Self {
        let mut result = self.clone();
        result *= other;
        result
    }
}

/// Multiplies by reference
impl<'a, E: ElimStrategy> Mul for &'a ElimMono<E> {
    type Output = ElimMono<E>;

    fn mul(self, other: &'a ElimMono<E>) -> ElimMono<E> {
        self.clone() * other.clone()
    }
}

impl<'a> Mul for &'a GrevLexTerm {
    type Output = GrevLexTerm;

    fn mul(self, other: &'a GrevLexTerm) -> GrevLexTerm {
        self.clone() * other.clone()
    }
}

/// Display for Monomials
impl<E: ElimStrategy> fmt::Display for ElimMono<E> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl fmt::Display for GrevLexTerm {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

/// Divides two terms. (var, power) pairs are combined by subtracting powers
impl<E: ElimStrategy> Div for ElimMono<E> {
    type Output = Option<Self>;

    fn div(self, other: Self) -> Option<Self> {
        self.0.div(other.0).map(ElimMono::from)
    }
}

impl Div for GrevLexTerm {
    type Output = Option<Self>;

    fn div(self, other: Self) -> Option<Self> {
        self.0.div(other.0).map(GrevLexTerm)
    }
}

/// Divides by reference
impl<'a, E: ElimStrategy> Div for &'a ElimMono<E> {
    type Output = Option<ElimMono<E>>;

    fn div(self, other: &'a ElimMono<E>) -> Option<ElimMono<E>> {
        self.clone() / other.clone()
    }
}

impl<'a> Div for &'a GrevLexTerm {
    type Output = Option<GrevLexTerm>;

    fn div(self, other: &'a GrevLexTerm) -> Option<GrevLexTerm> {
        self.clone() / other.clone()
    }
}

/// Convenience constructors from vectors of variables and exponents
impl<E: ElimStrategy> From<Vec<(PRef, usize)>> for ElimMono<E> {
    fn from(vars: Vec<(PRef, usize)>) -> Self {
        ElimMono::new(vars.into_iter().collect())
    }
}

impl From<Vec<(PRef, usize)>> for GrevLexTerm {
    fn from(vars: Vec<(PRef, usize)>) -> Self {
        GrevLexTerm::new(vars.into_iter().collect())
    }
}

/// Implement Monomial trait for GrevLexTerm
impl Monomial for GrevLexTerm {
    fn vars(&self) -> Vec<PRef> {
        self.0.vars()
    }
    fn powers(&self) -> Vec<usize> {
        self.0.powers()
    }
    fn is_constant(&self) -> bool {
        self.0.is_constant()
    }

    fn evaluate<F: Field>(&self, p: &Ctx<PRef, F>) -> F {
        self.0.evaluate(p)
    }
    fn is_divided(&self, other: &Self) -> bool {
        self.0.is_divided(&other.0)
    }

    fn lcm(&self, other: &Self) -> Self {
        GrevLexTerm(self.0.lcm(&other.0))
    }

    fn gcd(&self, other: &Self) -> Self {
        GrevLexTerm(self.0.gcd(&other.0))
    }

    /// Override the default Buchberger backend: route through the
    /// external `ark-gb` crate, which is ~10000× faster than the in-tree
    /// implementation on Katsura/Cyclic-n.
    ///
    /// W is the packed monomial width. Caller must ensure W is appropriate.
    fn compute_reduced_gb<F: Field, const W: usize>(
        num_vars: usize,
        input: Vec<SparsePolynomial<F, Self>>,
    ) -> Vec<SparsePolynomial<F, Self>>
    where
        Self: Sized,
    {
        use crate::analyses::groebner::ark_gb_adapter::compute_reduced_gb_grevlex;
        compute_reduced_gb_grevlex::<F, W>(num_vars, input)
    }
}

/// Implement Monomial trait for ElimMono<E>
impl<E: ElimStrategy> Monomial for ElimMono<E> {
    fn vars(&self) -> Vec<PRef> {
        self.0.vars()
    }

    fn powers(&self) -> Vec<usize> {
        self.0.powers()
    }
    fn is_constant(&self) -> bool {
        self.0.is_constant()
    }
    fn evaluate<F: Field>(&self, p: &Ctx<PRef, F>) -> F {
        self.0.evaluate(p)
    }
    fn is_divided(&self, other: &Self) -> bool {
        self.0.is_divided(&other.0)
    }
    fn lcm(&self, other: &Self) -> Self {
        ElimMono(self.0.lcm(&other.0), std::marker::PhantomData)
    }
    fn gcd(&self, other: &Self) -> Self {
        ElimMono(self.0.gcd(&other.0), std::marker::PhantomData)
    }

    /// Override the default Buchberger backend: route through the
    /// external `ark-gb` crate with an elim-aware monomial wrapper.
    /// See `ark_gb_adapter::compute_reduced_gb_with_elim` for the encoding.
    ///
    /// W is the packed monomial width. Caller must ensure W is appropriate.
    fn compute_reduced_gb<F: Field, const W: usize>(
        num_vars: usize,
        input: Vec<SparsePolynomial<F, Self>>,
    ) -> Vec<SparsePolynomial<F, Self>>
    where
        Self: Sized,
    {
        use crate::analyses::groebner::ark_gb_adapter::compute_reduced_gb_with_elim;
        compute_reduced_gb_with_elim::<F, Self, W>(num_vars, input, E::eliminate_var)
    }
}

/// Block-elimination order: first compare the elimination block (variables for
/// which `E::eliminate_var` returns true) via grevlex, then the kept block
/// via grevlex.
impl<E: ElimStrategy> Ord for ElimMono<E> {
    fn cmp(&self, other: &Self) -> Ordering {
        let elim_self = MonoTerm(
            self.0
                .iter()
                .filter(|(var, _)| E::eliminate_var(var))
                .map(|(var, power)| (var.clone(), *power))
                .collect::<Ctx<PRef, usize>>(),
        );

        let elim_other = MonoTerm(
            other
                .0
                .iter()
                .filter(|(var, _)| E::eliminate_var(var))
                .map(|(var, power)| (var.clone(), *power))
                .collect::<Ctx<PRef, usize>>(),
        );

        match elim_self.grevlex(&elim_other) {
            Ordering::Equal => {}
            order => return order,
        };

        let keep_self = MonoTerm(
            self.0
                .iter()
                .filter(|(var, _)| !E::eliminate_var(var))
                .map(|(var, power)| (var.clone(), *power))
                .collect::<Ctx<PRef, usize>>(),
        );

        let keep_other = MonoTerm(
            other
                .0
                .iter()
                .filter(|(var, _)| !E::eliminate_var(var))
                .map(|(var, power)| (var.clone(), *power))
                .collect::<Ctx<PRef, usize>>(),
        );

        keep_self.grevlex(&keep_other)
    }
}

impl<E: ElimStrategy> PartialOrd for ElimMono<E> {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

/// Define grevlex order comparison.
impl Ord for GrevLexTerm {
    fn cmp(&self, other: &Self) -> Ordering {
        self.0.grevlex(&other.0)
    }
}

impl PartialOrd for GrevLexTerm {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl GrevLexTerm {
    /// Borrow the underlying `MonoTerm` (variable → exponent map).
    pub(crate) fn as_mono_term(&self) -> &MonoTerm {
        &self.0
    }
}

impl MonoTerm {
    /// Iterate `(variable, exponent)` pairs, sorted by `PRef` (BTreeMap order).
    pub(crate) fn iter_pairs(&self) -> impl Iterator<Item = (&PRef, &usize)> {
        self.0.iter()
    }
}
