[package]
name = "examples"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mle"
path = "src/mle_example/main.rs"

[[bin]]
name = "kzg"
path = "src/kzg/main.rs"

[dependencies]
cli = { path = "../cli" }
ark-std = "0.5.0"
ark-ff =  { git = "https://github.com/arkworks-rs/algebra.git" }
backend = { path = "../backend" }
lang = { path = "../lang" }
share = { path = "../share" }
rand = { version = "0.8", features = ["std"] }