use rand::Rng;
use std::fmt;
use thiserror::Error;

use crate::typ::Size;
use share::traversal::ToTraversal1;
use share::{BoxAllocator, DocAllocator, DocBuilder, Pretty};

#[derive(Error, PartialEq, Debug)]
pub enum RangeError {
    #[error("Instantiated an invalid range [{0},{1}..{2}]")]
    RangeOrder(usize, usize, usize),
}

/// Represents a range of numbers
#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Clone, Hash)]
pub struct Range<N> {
    pub start: N,
    pub step: N,
    pub end: N,
}

/// Implementations of this trait can modify ranges
pub trait RangeTraversal<N>: Sized {
    fn range_traverse<E>(
        self,
        f: &mut dyn FnMut(Range<N>) -> Result<Range<N>, E>,
    ) -> Result<Self, E>;
}

impl<N> ToTraversal1<N> for Range<N> {
    type Output<Z> = Range<Z>;
    fn traverse1<Z, E>(self, f: &mut dyn FnMut(N) -> Result<Z, E>) -> Result<Range<Z>, E> {
        Ok(Range {
            start: f(self.start)?,
            step: f(self.step)?,
            end: f(self.end)?,
        })
    }
}

impl Default for Range<Size> {
    fn default() -> Self {
        Range {
            start: Size::zero(),
            step: Size::one(),
            end: Size::one(),
        }
    }
}

impl Default for CRange {
    fn default() -> Self {
        Range {
            start: 0,
            step: 1,
            end: 1,
        }
    }
}

/// Concrete sized range of numbers
pub type CRange = Range<usize>;
impl Copy for CRange {}

impl CRange {
    pub fn new(start: usize, end: usize) -> Self {
        Range {
            start,
            step: 1,
            end,
        }
    }
    /// Create a range from a start, step and end numbers, checking their order
    pub fn from_num(start: usize, step: usize, end: usize) -> Result<Self, RangeError> {
        // Check if the range is well formed
        let rs = Range { start, step, end };
        if (start <= end)
            && (step > 0)
            && end
                .checked_sub(start)
                .map(|d| d.is_multiple_of(step))
                .unwrap_or(false)
        {
            Ok(rs)
        } else {
            Err(RangeError::RangeOrder(start, step, end))
        }
    }

    pub fn check(&self) -> Result<(), RangeError> {
        Range::from_num(self.start, self.step, self.end).map(|_| ())
    }

    /// Create a singleton range
    pub fn singleton(start: usize) -> Self {
        Range {
            start,
            step: 1,
            end: start.checked_add(1).expect("singleton: start + 1 overflow"),
        }
    }

    pub fn random<R: Rng>(&self, rng: &mut R) -> usize {
        let offset = (rng.next_u32() % (self.len() as u32)) as usize;
        self.start
            .checked_add(
                offset
                    .checked_mul(self.step)
                    .expect("random: offset * step overflow"),
            )
            .expect("random: start + offset*step overflow")
    }

    /// Function to check if a value is contained in the range
    pub fn contains(&self, value: usize) -> bool {
        // Check if the value is within the bounds of the range
        if value < self.start || value >= self.end {
            return false;
        }

        // Check if the value aligns with the step
        (value - self.start).is_multiple_of(self.step)
    }

    pub fn concat(&self, other: &CRange) -> Option<CRange> {
        if self.step == other.step && self.end == other.start.checked_add(1)? {
            Some(Range {
                start: self.start,
                step: self.step,
                end: other.end,
            })
        } else {
            None
        }
    }

    pub fn is_zero(&self) -> bool {
        self.start == 0 && self.end <= self.step
    }

    pub fn len(&self) -> usize {
        (self.end - self.start) / self.step
    }

    pub fn is_empty(&self) -> bool {
        self.start >= self.end
    }

    /// Simplifies the composition of two ranges
    ///
    /// Given two ranges:
    /// - self: [x0, i0...y0]
    /// - other: [x1, i1...y1]
    ///
    /// The composition represents applying the second range to the sequence
    /// generated by the first range. For example, if:
    /// - [x0, i0...y0] generates sequence [a, b, c, d, e]
    /// - [x1, i1...y1] selects elements from this sequence
    ///
    /// The method calculates a new range that directly indexes the original array
    /// to produce the same result as the two ranges applied sequentially.
    ///
    /// Note: Ranges are end-exclusive, meaning elements are included up to but not
    /// including the 'end' value.
    ///
    /// Returns a new Range representing their composition
    pub fn compose(&self, other: &CRange) -> Option<CRange> {
        // Calculate the new start: original start + step * other.start
        let new_start = self
            .start
            .checked_add(self.step.checked_mul(other.start)?)?;

        // Calculate the new step: original step * other.step
        let new_step = self.step.checked_mul(other.step)?;

        // For end-exclusive ranges:
        // Calculate how many elements in the first range
        let elements_in_first = if self.start < self.end {
            (self.end - self.start).div_ceil(self.step)
        } else {
            0
        };

        // Calculate how many elements in the second range
        let elements_in_second = if other.start < other.end {
            (other.end - other.start).div_ceil(other.step)
        } else {
            0
        };

        // Calculate how many elements will be in the composed range
        // The minimum of elements available in the first range after the start point
        // and the number of elements the second range would select
        let elements_in_result = std::cmp::min(
            elements_in_first.saturating_sub(other.start),
            elements_in_second,
        );

        // Calculate the new end
        let new_end = new_start.checked_add(new_step.checked_mul(elements_in_result)?)?;

        Some(Range {
            start: new_start,
            step: new_step,
            end: new_end,
        })
    }

    /// Gets the element at the specified index when the range is applied
    ///
    /// Given:
    /// - self: [x0, i0...y0]
    /// - j: an integer index
    ///
    /// Returns the effective index in the original array,
    /// panics if the index is out of bounds.
    pub fn compose_index(&self, j: usize) -> usize {
        let computed_index = self
            .start
            .checked_add(
                j.checked_mul(self.step)
                    .expect("compose_index: j * step overflow"),
            )
            .expect("compose_index: start + j*step overflow");

        // Check if the computed index is within the bounds of the range
        if computed_index < self.end {
            computed_index
        } else {
            panic!(
                "Index out of bounds: {} not in range [{}, {})",
                computed_index, self.start, self.end
            );
        }
    }

    /// Checked addition of two ranges. Returns `None` if any intermediate
    /// `usize` arithmetic overflows.
    pub fn checked_add(self, b: CRange) -> Option<CRange> {
        let a_max = self.end.checked_sub(self.step)?;
        let b_max = b.end.checked_sub(b.step)?;
        Some(Range {
            start: self.start.checked_add(b.start)?,
            step: num::integer::gcd(self.step, b.step),
            end: a_max.checked_add(b_max)?.checked_add(1)?,
        })
    }

    /// Checked subtraction of two ranges. Returns `None` if any intermediate
    /// `usize` arithmetic overflows or underflows.
    pub fn checked_sub(self, b: CRange) -> Option<CRange> {
        let b_max = b.end.checked_sub(b.step)?;
        let a_max = self.end.checked_sub(self.step)?;
        Some(Range {
            start: self.start.checked_sub(b_max)?,
            step: num::integer::gcd(self.step, b.step),
            end: a_max.checked_sub(b.start)?.checked_add(1)?,
        })
    }

    /// Checked multiplication of two ranges. Returns `None` if any
    /// intermediate `usize` arithmetic overflows.
    pub fn checked_mul(self, b: CRange) -> Option<CRange> {
        let a_min = self.start;
        let a_max = self.end.checked_sub(self.step)?;
        let b_min = b.start;
        let b_max = b.end.checked_sub(b.step)?;

        let p1 = a_min.checked_mul(b_min)?;
        let p2 = a_min.checked_mul(b_max)?;
        let p3 = a_max.checked_mul(b_min)?;
        let p4 = a_max.checked_mul(b_max)?;

        let new_start = p1.min(p2).min(p3).min(p4);
        let new_end = p1.max(p2).max(p3).max(p4).checked_add(1)?;

        let new_step = num::integer::gcd(
            self.step.checked_mul(b.step)?,
            num::integer::gcd(
                self.step.checked_mul(b.start)?,
                b.step.checked_mul(self.start)?,
            ),
        );

        Some(Range {
            start: new_start,
            step: new_step,
            end: new_end,
        })
    }

    /// Checked division of two ranges. Returns `None` if any intermediate
    /// `usize` arithmetic overflows or if the divisor range includes zero.
    pub fn checked_div(self, b: CRange) -> Option<CRange> {
        let a_min = self.start;
        let a_max = self.end.checked_sub(self.step)?;
        let b_min = b.start;
        let b_max = b.end.checked_sub(b.step)?;

        if b_min == 0 || b_max == 0 {
            return None;
        }

        let new_start = a_min / b_max;
        let new_end = (a_max / b_min).checked_add(1)?;

        Some(Range {
            start: new_start,
            step: 1,
            end: new_end,
        })
    }

    /// Checked remainder of two ranges. Returns `None` if any intermediate
    /// `usize` arithmetic overflows or if the divisor range includes zero.
    pub fn checked_rem(self, b: CRange) -> Option<CRange> {
        let a_min = self.start;
        let a_max = self.end.checked_sub(self.step)?;
        let b_min = b.start;
        let b_max = b.end.checked_sub(b.step)?;

        if b_min == 0 || b_max == 0 {
            return None;
        }

        let new_start = a_min % b_max;
        let new_end = (a_max % b_min).checked_add(1)?;

        Some(Range {
            start: new_start,
            step: 1,
            end: new_end,
        })
    }

    /// Checked exponentiation of two ranges. Returns `None` if any
    /// intermediate `usize` arithmetic overflows.
    pub fn checked_pow(self, b: CRange) -> Option<CRange> {
        let a_min = self.start;
        let a_max = self.end.checked_sub(self.step)?;
        let b_min = b.start;
        let b_max = b.end.checked_sub(b.step)?;

        let new_start = a_min.checked_pow(b_min as u32)?;
        let new_end = a_max.checked_pow(b_max as u32)?.checked_add(1)?;

        Some(Range {
            start: new_start,
            step: 1,
            end: new_end,
        })
    }
}

impl Iterator for CRange {
    type Item = usize;

    fn next(&mut self) -> Option<Self::Item> {
        if self.start >= self.end {
            None
        } else {
            let current = self.start;
            self.start = match self.start.checked_add(self.step) {
                Some(v) => v,
                None => self.end, // overflow: stop iteration
            };
            Some(current)
        }
    }
}

/// Pretty printer instance
impl<'a, D, A, N> Pretty<'a, D, A> for Range<N>
where
    D: DocAllocator<'a, A>,
    D::Doc: Clone,
    N: Pretty<'a, D, A>,
    A: 'a + Clone,
{
    fn pretty(self, allocator: &'a D) -> DocBuilder<'a, D, A> {
        allocator.concat([
            self.start.pretty(allocator),
            allocator.text(","),
            self.step.pretty(allocator),
            allocator.text(".."),
            self.end.pretty(allocator),
        ])
    }

    fn is_nil(&self) -> bool {
        false
    }
}

/// Display instance calls the pretty printer
impl<'a, N> fmt::Display for Range<N>
where
    N: Pretty<'a, BoxAllocator, ()> + Clone,
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        <Range<N> as Pretty<'_, BoxAllocator, ()>>::pretty(self.clone(), &BoxAllocator)
            .1
            .render_fmt(100, f)
    }
}

#[test]
fn range_traversal() {
    let r = Range {
        start: Size::varstr("N"),
        step: Size::from(2),
        end: Size::from(10),
    };
    assert_eq!(
        r.traverse1(&mut |x| x.eval(&share::Ctx::singleton("N".into(), 0)))
            .unwrap(),
        Range {
            start: 0,
            step: 2,
            end: 10
        }
    );
}

#[test]
fn checked_add_basic() {
    let a = CRange::new(1, 10);
    let b = CRange::new(2, 20);
    let r = a.checked_add(b).unwrap();
    assert_eq!(r.start, 3);
    assert_eq!(r.end, 29); // (10-1) + (20-1) + 1 = 9 + 19 + 1
}

#[test]
fn checked_add_overflow() {
    let a = CRange::new(usize::MAX - 5, usize::MAX);
    let b = CRange::new(1, 10);
    // start + b.start overflows
    assert_eq!(a.checked_add(b), None);
}

#[test]
fn checked_add_end_overflow() {
    let a = CRange::new(0, usize::MAX);
    let b = CRange::new(0, 2);
    // (MAX - 1) + (2 - 1) + 1 overflows
    assert_eq!(a.checked_add(b), None);
}

#[test]
fn checked_sub_basic() {
    let a = CRange::new(10, 20);
    let b = CRange::new(2, 5);
    let r = a.checked_sub(b).unwrap();
    assert_eq!(r.start, 6); // 10 - (5-1) = 10 - 4 = 6
    assert_eq!(r.end, 18); // (20-1) - 2 + 1 = 19 - 2 + 1
}

#[test]
fn checked_sub_underflow_start() {
    let a = CRange::new(1, 10);
    let b = CRange::new(5, 20);
    // a.start (1) - b_max (19) underflows
    assert_eq!(a.checked_sub(b), None);
}

#[test]
fn checked_sub_underflow_end() {
    let a = CRange::new(0, 3);
    let b = CRange::new(5, 10);
    // a_max (2) - b.start (5) underflows
    assert_eq!(a.checked_sub(b), None);
}

#[test]
fn checked_mul_basic() {
    let a = CRange::new(2, 5); // values 2,3,4
    let b = CRange::new(3, 7); // values 3,4,5,6
    let r = a.checked_mul(b).unwrap();
    assert_eq!(r.start, 6); // 2*3
    assert_eq!(r.end, 25); // 4*6 + 1
}

#[test]
fn checked_mul_overflow() {
    // Use values large enough that their product overflows usize.
    // sqrt(usize::MAX) ≈ 4294967296 on 64-bit, so two values > that will overflow.
    let big = (usize::MAX as f64).sqrt() as usize + 1;
    let a = CRange::new(big, big + 1); // singleton {big}
    let b = CRange::new(big, big + 1); // singleton {big}
                                       // big * big overflows
    assert_eq!(a.checked_mul(b), None);
}

#[test]
fn checked_mul_step_overflow() {
    let a = CRange {
        start: 0,
        step: usize::MAX,
        end: usize::MAX,
    };
    let b = CRange {
        start: 0,
        step: 2,
        end: 3,
    };
    // step * b.step = MAX * 2 overflows
    assert_eq!(a.checked_mul(b), None);
}

#[test]
fn checked_div_basic() {
    let a = CRange::new(0, 10);
    let b = CRange::new(1, 3);
    let r = a.checked_div(b).unwrap();
    assert_eq!(r.start, 0); // 0 / 2
    assert_eq!(r.end, 10); // 9 / 1 + 1
}

#[test]
fn checked_div_by_zero() {
    let a = CRange::new(0, 10);
    let b = CRange::new(0, 3); // includes 0
    assert_eq!(a.checked_div(b), None);
}

#[test]
fn checked_div_b_max_zero() {
    // b_max = end - step = 1 - 1 = 0 → division by zero
    let a = CRange::new(10, 20);
    let b = CRange {
        start: 0,
        step: 1,
        end: 1, // b_max = 0
    };
    assert_eq!(a.checked_div(b), None);
}

#[test]
fn checked_rem_basic() {
    let a = CRange::new(0, 10); // values 0..9
    let b = CRange::new(1, 3); // values 1,2
    let r = a.checked_rem(b).unwrap();
    assert_eq!(r.start, 0); // 0 % 2 = 0
    assert_eq!(r.end, 1); // 9 % 1 + 1 = 0 + 1
}

#[test]
fn checked_rem_by_zero() {
    let a = CRange::new(0, 10);
    let b = CRange::new(0, 3); // includes 0
    assert_eq!(a.checked_rem(b), None);
}

#[test]
fn checked_pow_basic() {
    let a = CRange::new(2, 4); // values 2,3
    let b = CRange::new(2, 4); // values 2,3
    let r = a.checked_pow(b).unwrap();
    assert_eq!(r.start, 4); // 2^2
    assert_eq!(r.end, 28); // 3^3 + 1 = 27 + 1
}

#[test]
fn checked_pow_overflow() {
    let a = CRange::new(2, 3);
    let b = CRange::new(64, 65); // 2^64 overflows usize on 64-bit
    assert_eq!(a.checked_pow(b), None);
}

#[test]
fn checked_pow_end_overflow() {
    // (usize::MAX - 1)^2 overflows usize
    let big = usize::MAX - 1;
    let a = CRange::new(big, big + 1); // singleton {big} — big+1 = MAX, fits
    let b = CRange::new(2, 3); // singleton {2}
                               // big^2 overflows
    assert_eq!(a.checked_pow(b), None);
}

#[test]
fn compose_overflow_returns_none() {
    // step * other.step = MAX * 2 overflows
    let a = CRange {
        start: 0,
        step: usize::MAX,
        end: usize::MAX,
    };
    let b = CRange {
        start: 0,
        step: 2,
        end: 3,
    };
    assert_eq!(a.compose(&b), None);
}

#[test]
fn iterator_stops_on_overflow() {
    let r = CRange {
        start: usize::MAX - 1,
        step: 2,
        end: usize::MAX,
    };
    // First: start=MAX-1 (< MAX), yield MAX-1, then start = (MAX-1)+2 overflows → start=end
    let mut it = r;
    assert_eq!(it.next(), Some(usize::MAX - 1));
    assert_eq!(it.next(), None);
}
