use from_pest::{ConversionError, FromPest};
use pest::iterators::Pairs;
use std::fmt;
use std::ops::{Add, Sub, Mul, Div, BitXor};

use thiserror::Error;

use share::{Pretty, Traversal, DocAllocator, DocBuilder, BoxAllocator, Ctx};
use share::traversal::ToTraversal1;
use crate::typ::Size;
use crate::eval::Eval;
use crate::parser::*;


#[derive(Error, PartialEq, Debug)]
pub enum RangeError {
    #[error("Instantiated an invalid range [{0},{1}..{2}]")]
    RangeOrder(usize, usize, usize),
}

/// Represents a range of numbers
#[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Clone, Hash)]
pub struct Range<N> {
    pub start : N,
    pub step : N,
    pub end : N
}

/// Implementations of this trait can modify ranges
pub trait RangeTraversal<N> : Sized {
    fn range_traverse<E>(self, f: &mut dyn FnMut(Range<N>) -> Result<Range<N>, E>) -> Result<Self, E>;
}

impl<N> ToTraversal1<N> for Range<N> {
    type Output<Z> = Range<Z>;
    fn traverse1<Z, E>(self, f: &mut dyn FnMut(N) -> Result<Z, E>) -> Result<Range<Z>, E> {
        Ok(Range {
            start: f(self.start)?,
            step: f(self.step)?,
            end: f(self.end)?
        })
    }
}

/// Concrete sized range of numbers
pub type CRange = Range<usize>;
impl Copy for CRange {}

impl CRange {
    pub fn new(start: usize, end: usize) -> Self {
        Range { start, step: 1, end }
    }
    /// Create a range from a start, step and end numbers, checking their order
    pub fn from_num(start: usize, step: usize, end: usize) -> Result<Self, RangeError> {
        // Check if the range is well formed
        let rs = Range { start, step, end };
        if (start <= end) &&  (step > 0) && ((end - start) % step == 0) {
            Ok(rs)
        } else {
            Err(RangeError::RangeOrder(start, step, end))
        }
    }

    pub fn check(&self) -> Result<(), RangeError> {
        Range::from_num(self.start, self.step, self.end).map(|_| ())
    }

    /// Create a singleton range
    pub fn singleton(start: usize) -> Self {
        Range { start, step: 1, end: start + 1 }
    }

    /// Function to check if a value is contained in the range
    pub fn contains(&self, value: usize) -> bool {
        // Check if the value is within the bounds of the range
        if value < self.start || value >= self.end {
            return false;
        }

        // Check if the value aligns with the step
        (value - self.start) % self.step == 0
    }

    pub fn get_size(&self) -> usize {
        (self.end - self.start) / self.step
    }

    /// Simplifies the composition of two ranges
    ///
    /// Given two ranges:
    /// - self: [x0, i0...y0]
    /// - other: [x1, i1...y1]
    ///
    /// The composition represents applying the second range to the sequence
    /// generated by the first range. For example, if:
    /// - [x0, i0...y0] generates sequence [a, b, c, d, e]
    /// - [x1, i1...y1] selects elements from this sequence
    ///
    /// The method calculates a new range that directly indexes the original array
    /// to produce the same result as the two ranges applied sequentially.
    ///
    /// Note: Ranges are end-exclusive, meaning elements are included up to but not
    /// including the 'end' value.
    ///
    /// Returns a new Range representing their composition
    pub fn compose(&self, other: &CRange) -> CRange {
        // Calculate the new start: original start + step * other.start
        let new_start = self.start + self.step * other.start;

        // Calculate the new step: original step * other.step
        let new_step = self.step * other.step;

        // For end-exclusive ranges:
        // Calculate how many elements in the first range
        let elements_in_first = if self.start < self.end {
            (self.end - self.start + self.step - 1) / self.step
        } else {
            0
        };

        // Calculate how many elements in the second range
        let elements_in_second = if other.start < other.end {
            (other.end - other.start + other.step - 1) / other.step
        } else {
            0
        };

        // Calculate how many elements will be in the composed range
        // The minimum of elements available in the first range after the start point
        // and the number of elements the second range would select
        let elements_in_result = std::cmp::min(
            elements_in_first.saturating_sub(other.start),
            elements_in_second
        );

        // Calculate the new end
        let new_end = new_start + new_step * elements_in_result;

        Range { start: new_start, step:new_step, end: new_end }
    }

    /// Gets the element at the specified index when the range is applied
    ///
    /// Given:
    /// - self: [x0, i0...y0]
    /// - j: an integer index
    ///
    /// Returns the effective index in the original array,
    /// or None if the index is out of bounds
    pub fn compose_index(&self, j: usize) -> Option<usize> {
        let computed_index = self.start + j * self.step;

        // Check if the computed index is within the bounds of the range
        if computed_index < self.end {
            Some(computed_index)
        } else {
            None
        }
    }

}

pub struct RangeTraversal1<N>(std::marker::PhantomData<N>);
impl<A, B> Traversal<A, B> for RangeTraversal1<A> {
    type Domain = Range<A>;
    type Codomain = Range<B>;
    fn traverse<E>(
        on: Self::Domain,
        f: &mut dyn FnMut(A) -> Result<B, E>,
    ) -> Result<Self::Codomain, E> {
        Ok(Range {
            start: f(on.start)?,
            step: f(on.step)?,
            end: f(on.end)?,
        })
    }
}

impl Iterator for CRange {
    type Item = usize;

    fn next(&mut self) -> Option<Self::Item> {
        if self.start >= self.end {
            None
        } else {
            let current = self.start;
            self.start = self.start.saturating_add(self.step);
            Some(current)
        }
    }
}

/// Pretty printer instance
impl<'a, D, A, N> Pretty<'a, D, A> for Range<N>
where
    D: DocAllocator<'a, A>,
    D::Doc: Clone,
    N: Pretty<'a, D, A>,
    A: 'a + Clone,
{
    fn pretty(self, allocator: &'a D) -> DocBuilder<'a, D, A> {
        allocator.concat([
            self.start.pretty(allocator),
            allocator.text(","),
            self.step.pretty(allocator),
            allocator.text(".."),
            self.end.pretty(allocator),
        ])
    }

    fn is_nil(&self) -> bool {
        false
    }
}

impl Add for CRange {
    type Output = CRange;

    fn add(self, b: CRange) -> CRange {
        Range {
            start: self.start + b.start,
            step: num::integer::gcd(self.step, b.step),
            end: (self.end - self.step) + (b.end - b.step) + 1
        }
    }
}

impl Sub for CRange {
    type Output = CRange;

    fn sub(self, b: CRange) -> CRange {
        Range {
            start: self.start.saturating_sub(b.end - b.step),
            step: num::integer::gcd(self.step, b.step),
            end: (self.end - self.step) - (b.start) + 1
        }
    }
}

impl Mul for CRange {
    type Output = CRange;

    fn mul(self, b: CRange) -> CRange {
        let a_min = self.start;
        let a_max = self.end - self.step;
        let b_min = b.start;
        let b_max = b.end - b.step;

        // Compute all possible products
        let p1 = a_min * b_min;
        let p2 = a_min * b_max;
        let p3 = a_max * b_min;
        let p4 = a_max * b_max;

        // Compute new start and end
        let new_start = p1.min(p2).min(p3).min(p4);
        let new_end = p1.max(p2).max(p3).max(p4) + 1;

        // Compute new step
        let new_step = num::integer::gcd(self.step * b.step, num::integer::gcd(self.step * b.start, b.step * self.start));

        Range {
            start: new_start,
            step: new_step,
            end: new_end,
        }
    }
}

impl Div for CRange {
    type Output = CRange;

    fn div(self, b: CRange) -> CRange {
        let a_min = self.start;
        let a_max = self.end - self.step;
        let b_min = b.start;
        let b_max = b.end - b.step;

        // Compute new start and end
        let new_start = a_min / b_max; // Smallest quotient
        let new_end = a_max / b_min + 1; // Largest quotient + 1 (right-exclusive)

        // Use a step of 1 for safe overapproximation
        let new_step = 1;

        Range {
            start: new_start,
            step: new_step,
            end: new_end,
        }
    }
}

impl BitXor for CRange {
    type Output = CRange;

    fn bitxor(self, b: CRange) -> CRange {
        let a_min = self.start;
        let a_max = self.end - self.step;
        let b_min = b.start;
        let b_max = b.end - b.step;

        // Compute new start and end
        let new_start = a_min.pow(b_min as u32); // Smallest power
        let new_end = a_max.pow(b_max as u32) + 1; // Largest power + 1 (right-exclusive)

        // Use a step of 1 for safe overapproximation
        let new_step = 1;

        Range {
            start: new_start,
            step: new_step,
            end: new_end,
        }
    }
}

/// Display instance calls the pretty printer
impl<'a, N> fmt::Display for Range<N> where N: Pretty<'a, BoxAllocator, ()> + Clone {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        <Range<N> as Pretty<'_, BoxAllocator, ()>>::pretty(self.clone(), &BoxAllocator)
            .1
            .render_fmt(100, f)
    }
}

impl<'pest> FromPest<'pest> for CRange {
    type Rule = Rule;
    type FatalError = InputError<'pest>;

    fn from_pest(
        pest: &mut Pairs<'pest, Self::Rule>,
    ) -> Result<Self, ConversionError<Self::FatalError>> {
        let r: Range<Size> = Range::from_pest(pest)?;
        // Evaluate Size with empty context ~ cast to usize
        let start = r.start.eval(&Ctx::new())?;
        let step = r.step.eval(&Ctx::new())?;
        let end = r.end.eval(&Ctx::new())?;

        // Check if the range is well formed
        Ok(Range::from_num(start, step, end)?)
    }
}

impl<'pest> FromPest<'pest> for Range<Size> {
    type Rule = Rule;
    type FatalError = InputError<'pest>;

    fn from_pest(
        pest: &mut Pairs<'pest, Self::Rule>,
    ) -> Result<Self, ConversionError<Self::FatalError>> {
        let pair = pest.next().ok_or(ConversionError::NoMatch)?;
        match pair.as_rule() {
            Rule::range => {
                let mut inner = pair.into_inner();
                if inner.len() == 3 {
                    let start = Size::from_pest(&mut Pairs::single(inner.next().unwrap()))?;
                    let step = Size::from_pest(&mut Pairs::single(inner.next().unwrap()))?;
                    let end = Size::from_pest(&mut Pairs::single(inner.next().unwrap()))?;
                    Ok(Range { start, step, end })
                } else {
                    let start = Size::from_pest(&mut Pairs::single(inner.next().unwrap()))?;
                    let end = Size::from_pest(&mut Pairs::single(inner.next().unwrap()))?;
                    Ok(Range { start, step: Size::one(), end })
                }
            },
            _ => unreachable!()
        }
    }
}

#[cfg(test)] use pest::Parser;
#[test]
fn range_parser() {
    let mut pairs = ZippelParser::parse(Rule::range, "0..10").unwrap();
    assert_eq!(Range::from_pest(&mut pairs).unwrap(), Range { start: Size::from(0), step: Size::one(), end: Size::from(10) });

    pairs = ZippelParser::parse(Rule::range, "0, 2..2^N").unwrap();
    assert_eq!(Range::from_pest(&mut pairs).unwrap(), Range { start: Size::from(0), step: Size::from(2), end: Size::from(2) ^ Size::from("N") });
}

#[test]
fn range_traversal() {
    let r = Range { start: Size::varstr("N"), step: Size::from(2), end: Size::from(10) };
    assert_eq!(
        r.traverse1(&mut |x| x.eval(&Ctx::singleton("N".into(), 0))).unwrap(),
        Range { start: 0, step: 2, end: 10 }
    );
}
