//! Monomorphic grevlex engine: zippel `GrevLexTerm` ↔ ark-gb `GrevLexTerm<W>`.

use super::{EngineError, RingSnapshot, W, collect_prefs, make_ring, unit_basis_if_constant};
use crate::PRef;
use crate::analyses::groebner::{GrevLexTerm, SparsePolynomial};
use ark_ff::Field;
use ark_gb::{GrevLexTerm as ArkGrevLexTerm, MonoTerm as ArkMonoTerm, Poly, compute_gb};
use share::Ctx;
use std::collections::BTreeMap;

/// Build a snapshot for a grevlex workload: union of PRefs sorted
/// ascending, assigned dense ark-gb indices `0..nvars-1`. PRef-greater ⇔
/// ark-rightmost (preserves grevlex on round-trip).
fn build_snapshot<F: Field + Copy + Send + Sync>(
    polys: &[SparsePolynomial<F, GrevLexTerm>],
) -> Result<RingSnapshot<F>, EngineError> {
    let prefs = collect_prefs(polys);
    let slots: Vec<Option<PRef>> = prefs.into_iter().map(Some).collect();
    let ring = make_ring(slots.len())?;
    Ok(RingSnapshot { ring, slots })
}

/// Build the forward (PRef → ark-index) lookup. Done once per call,
/// reused across all term conversions.
fn pref_to_idx<F: Field + Copy + Send + Sync>(snap: &RingSnapshot<F>) -> BTreeMap<PRef, u32> {
    let mut map = BTreeMap::new();
    for (i, slot) in snap.slots.iter().enumerate() {
        if let Some(p) = slot {
            map.insert(p.clone(), i as u32);
        }
    }
    map
}

/// Convert one zippel `SparsePolynomial<F, GrevLexTerm>` into an ark-gb
/// `Poly<F, ArkGrevLexTerm<W>, W>` in a single pass over each term's
/// `Ctx<PRef, usize>` (no `Vec<(PRef, usize)>` intermediate).
fn poly_to_ark<F: Field + Copy + Send + Sync>(
    snap: &RingSnapshot<F>,
    fwd: &BTreeMap<PRef, u32>,
    p: &SparsePolynomial<F, GrevLexTerm>,
) -> Result<Poly<F, ArkGrevLexTerm<W>, W>, EngineError> {
    let nvars = snap.nvars() as usize;
    let max_exp = ark_gb::ring::MAX_VAR_EXP;
    let mut terms: Vec<(F, ArkGrevLexTerm<W>)> = Vec::with_capacity(p.terms.len());
    let mut exps = vec![0u32; nvars];

    for (mono, coef) in p.terms.iter() {
        if coef.is_zero() {
            continue;
        }
        for slot in exps.iter_mut() {
            *slot = 0;
        }
        for (var, power) in mono.iter() {
            if (*power as u32) > max_exp {
                return Err(EngineError::ExponentOverflow {
                    var: var.clone(),
                    exponent: *power,
                    max: max_exp,
                });
            }
            let idx = *fwd
                .get(var)
                .expect("engine: PRef in poly term not present in snapshot")
                as usize;
            exps[idx] = *power as u32;
        }
        let mt = ArkMonoTerm::<W>::from_exponents(&snap.ring, &exps).expect(
            "engine: ark MonoTerm packing failed after caps verified \
             (this is a bug in the engine, not in the workload)",
        );
        terms.push((*coef, ArkGrevLexTerm::<W>::from(mt)));
    }
    Ok(Poly::from_terms(&snap.ring, terms))
}

/// Convert an ark-gb `Poly<F, ArkGrevLexTerm<W>, W>` back into zippel's
/// `SparsePolynomial<F, GrevLexTerm>`. Each term: unpack ark exponents,
/// write directly into a fresh `Ctx<PRef, usize>` (no `Vec<(PRef, usize)>`
/// intermediate).
fn ark_to_poly<F: Field + Copy + Send + Sync>(
    snap: &RingSnapshot<F>,
    p: &Poly<F, ArkGrevLexTerm<W>, W>,
) -> SparsePolynomial<F, GrevLexTerm> {
    use ark_gb::Monomial as ArkMonomial;
    let mut out: Ctx<GrevLexTerm, F> = Ctx::default();
    let nvars = snap.nvars() as usize;

    for (coef, mono) in p.iter() {
        if coef.is_zero() {
            continue;
        }
        let exps: Vec<u32> = ArkGrevLexTerm::<W>::exponents(mono, &snap.ring);
        let mut ctx: Ctx<PRef, usize> = Ctx::default();
        for (i, e) in exps.iter().enumerate().take(nvars) {
            if *e == 0 {
                continue;
            }
            let pref = snap.slots[i]
                .clone()
                .expect("engine: ark-gb produced exponent on ghost slot");
            let exp = *e as usize;
            ctx.insert(&pref, &exp);
        }
        let term = GrevLexTerm::new(ctx);
        out.insert(&term, &coef);
    }
    SparsePolynomial { terms: out }
}

/// Compute a *reduced* Gröbner basis of the ideal generated by `polys`
/// under the grevlex order. Routes through ark-gb's `compute_gb`.
pub fn compute_gb_grevlex<F: Field + Copy + Send + Sync + 'static>(
    polys: &[SparsePolynomial<F, GrevLexTerm>],
) -> Vec<SparsePolynomial<F, GrevLexTerm>> {
    let nonzero: Vec<&SparsePolynomial<F, GrevLexTerm>> =
        polys.iter().filter(|p| !p.is_zero()).collect();
    if nonzero.is_empty() {
        return Vec::new();
    }

    // Constant-ideal short-circuit: ark-gb refuses `nvars = 0`.
    if super::collect_prefs(polys).is_empty() {
        return unit_basis_if_constant(&nonzero).unwrap_or_default();
    }

    let snap = build_snapshot(polys).unwrap_or_else(|e| panic!("{}", e));
    let fwd = pref_to_idx(&snap);
    let ark_inputs: Vec<Poly<F, ArkGrevLexTerm<W>, W>> = nonzero
        .iter()
        .map(|p| poly_to_ark(&snap, &fwd, p).unwrap_or_else(|e| panic!("{}", e)))
        .collect();

    compute_gb(snap.ring.clone(), ark_inputs)
        .iter()
        .map(|p| ark_to_poly(&snap, p))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use ark_bls12_381::Fr;
    use ark_ff::One;
    use backend::ATyp;
    use lang::id::Vid;
    use lang::typ::{Distribution, Qualifier};
    use petgraph::graph::NodeIndex;

    fn pref_for(name: &str) -> PRef {
        PRef::from_var(
            Vid::new(name),
            NodeIndex::new(0),
            ATyp::scalar(),
            0,
            Qualifier::Public,
            Distribution::Nonuniform,
        )
    }

    fn mono(parts: Vec<(&str, usize)>) -> GrevLexTerm {
        let mut ctx: Ctx<PRef, usize> = Ctx::default();
        for (name, p) in parts {
            ctx.insert(&pref_for(name), &p);
        }
        GrevLexTerm::new(ctx)
    }

    fn term(c: i64, parts: Vec<(&str, usize)>) -> SparsePolynomial<Fr, GrevLexTerm> {
        let mut terms: Ctx<GrevLexTerm, Fr> = Ctx::default();
        let m = mono(parts);
        let coef = if c < 0 {
            -Fr::from((-c) as u64)
        } else {
            Fr::from(c as u64)
        };
        terms.insert(&m, &coef);
        SparsePolynomial { terms }
    }

    fn add(
        a: SparsePolynomial<Fr, GrevLexTerm>,
        b: SparsePolynomial<Fr, GrevLexTerm>,
    ) -> SparsePolynomial<Fr, GrevLexTerm> {
        a + b
    }

    #[test]
    fn round_trip_preserves_polynomial() {
        let p = add(
            add(term(3, vec![("a", 2)]), term(2, vec![("a", 1), ("b", 1)])),
            term(7, vec![]),
        );
        let snap = build_snapshot(std::slice::from_ref(&p)).unwrap();
        let fwd = pref_to_idx(&snap);
        let ark = poly_to_ark(&snap, &fwd, &p).unwrap();
        let back = ark_to_poly(&snap, &ark);
        assert_eq!(p, back);
    }

    #[test]
    fn order_tie_break_a2_vs_bc() {
        let p = add(term(1, vec![("a", 2)]), term(1, vec![("b", 1), ("c", 1)]));
        let snap = build_snapshot(std::slice::from_ref(&p)).unwrap();
        let fwd = pref_to_idx(&snap);
        let leading_zippel = p.terms.iter().next().map(|(t, _)| t.clone()).unwrap();
        assert_eq!(leading_zippel, mono(vec![("a", 2)]));

        let ark = poly_to_ark(&snap, &fwd, &p).unwrap();
        let back = ark_to_poly(&snap, &ark);
        let leading_back = back.terms.iter().next().map(|(t, _)| t.clone()).unwrap();
        assert_eq!(leading_back, mono(vec![("a", 2)]));
        assert_eq!(p, back);
    }

    #[test]
    fn exponent_127_ok() {
        let p = term(1, vec![("a", 127)]);
        let snap = build_snapshot(std::slice::from_ref(&p)).unwrap();
        let fwd = pref_to_idx(&snap);
        let _ark = poly_to_ark(&snap, &fwd, &p).unwrap();
    }

    #[test]
    fn exponent_128_panics_via_engine_error() {
        let p = term(1, vec![("a", 128)]);
        let snap = build_snapshot(std::slice::from_ref(&p)).unwrap();
        let fwd = pref_to_idx(&snap);
        let res = poly_to_ark(&snap, &fwd, &p);
        match res {
            Err(EngineError::ExponentOverflow { exponent, max, .. }) => {
                assert_eq!(exponent, 128);
                assert_eq!(max, 0x7F);
            }
            other => panic!("expected ExponentOverflow, got {:?}", other),
        }
    }

    #[test]
    fn nvars_64_panics() {
        let mut p = term(0, vec![]);
        for i in 0..64 {
            let name = format!("v{}", i);
            let leaked: &'static str = Box::leak(name.into_boxed_str());
            p = p + term(1, vec![(leaked, 1)]);
        }
        let res = build_snapshot(std::slice::from_ref(&p));
        match res {
            Err(EngineError::TooManyVars { nvars, max }) => {
                assert_eq!(nvars, 64);
                assert_eq!(max, 63);
            }
            other => panic!("expected TooManyVars, got {:?}", other),
        }
    }

    #[test]
    fn compute_gb_simple_linear() {
        let p1 = add(term(1, vec![("a", 1)]), term(1, vec![("b", 1)]));
        let p2 = add(term(1, vec![("a", 1)]), term(-1, vec![("b", 1)]));
        let gb = compute_gb_grevlex(&[p1, p2]);
        assert_eq!(gb.len(), 2);
        for p in &gb {
            assert_eq!(p.terms.len(), 1);
            let (_, c) = p.terms.iter().next().unwrap();
            assert!(c.is_one());
        }
    }
}
