[package]
name = "lang"
version = "0.1.0"
edition = "2021"
authors = ["Lef Ioannidis <elefthei@seas.upenn.edu>", "Alireza Shirzad <alrshir@seas.upenn.edu>"]

[dependencies]
share = { path = "../share" }
lazy_static = "1.4.0"
thiserror = "1.0.58"
arbitrary = "1.4.1"
num = "0.4.3"
rand = { version = "0.8", features = ["std"] }
logos = "0.14"
chumsky = { version = "0.13", features = ["pratt"] }
ariadne = "0.5"
lang-derive = { path = "./lang-derive" }

[dev-dependencies]
arbtest = "0.3.1"
insta = { version = "1.48", features = ["yaml"] }
yansi = "1.0"

[lib]
doctest = false
