WHITESPACE = _{ " " | "\n" | "\t" }
positive = @{ ASCII_DIGIT+ }
one = @{ "1" }
two = @{ "2" }
add_op = @{ "+" }
sub_op = @{ "-" }
mul_op = @{ "*" }
div_op = @{ "/" }
pow_op = @{ "^" }
dot_op = @{ "." }
concat_op = @{ "++" }
eq_op = @{ "==" }
le_op = @{ "<=" }
lt_op = @{ "<" }
ge_op = @{ ">=" }
gt_op = @{ ">" }
and_op = @{ "&&" }
or_op  = @{ "||" }
in_op  = @{ "in" }

/// Identifiers for functions, variables, type variables
keyword = {"let" | "fn" | "proto" }
id = @{ !(keyword ~ !ASCII_ALPHANUMERIC) ~ (ASCII_ALPHANUMERIC | "_" | "'" )+ }

/// Ranges appear in types and expressions
range = { size_ty ~ ("," ~ size_ty)? ~ ".." ~ size_ty }

/// Type-level size arithmetic
size_ty  = { size_ty_term ~ (size_bin_op ~ size_ty_term)* }
    size_bin_op   = _{ add_op | sub_op | mul_op | div_op | pow_op }
    size_var      = { id }
    size_ty_term  = _{ "(" ~ size_ty ~ ")" | positive | size_var }

/// Base kinds
kind_ty = { field_ty | group_ty | range_ty | pairing_ty | multiplicative_ty }
    field_ty          = { "Field" }
    group_ty          = { "Group" }
    pairing_ty        = { "Pairing" ~ "<" ~ id ~ "," ~ id ~ ">" }
    multiplicative_ty = { "Multiplicative" ~ "<" ~ id ~ ">" }
    range_ty          = { range }

typ = _{ uni_ty | mle_ty | vec_ty | fin_ty | bool_ty | base_ty }
    base_ty = { id }                                     // Base type variable
    uni_ty = { "Uni" ~ "<" ~ id ~ "," ~ size_ty ~ ">" }  // Univariate polynomial
    mle_ty = { "Mle" ~ "<" ~ id ~ "," ~ size_ty ~ ">" }  // Multilinear expression
    fin_ty = { "Fin" ~ "<" ~ range ~ ">"  }              // Index type
    vec_ty = { "[" ~ typ ~ ";" ~ size_ty ~ "]" }         // Vector type
    bool_ty = { "Bool" }                                 // Boolean type

/// Arithmetic expression language of Zippel
aexp       = { aexp_term ~ (bin_op ~ aexp_term)* }
aexp_term  = _{ "(" ~ aexp ~ ")"
         | gen_exp
         | coef_exp
         | mle_exp
         | interp_exp
         | challenge_exp
         | random_exp
         | map_exp
         | vec_exp
         | ram_exp
         | range_exp
         | app_exp
         | assert_exp
         | verify_exp
         | let_exp
         | log_exp
         | positive
         | id
    }
    gen_exp       = { "gen" ~ "<" ~ id ~ ">" }                         // Group generator
    coef_exp      = { "coef" ~ aexp  }                                 // Create a univariate polynomial
    mle_exp       = { "mle"  ~ aexp  }                                 // Create a multilinear expression
    interp_exp    = { "interpolate" ~ "(" ~ aexp ~ "," ~ aexp ~ ")" }  // Interpolate (FFT) with domain and values
    random_exp    = { "random" ~ "<" ~ id ~ ">" }                      // Uniform random sampling (Prover)
    challenge_exp = { "challenge" ~ "<" ~ id ~ ">" }                   // Random oracle challenge (Verifier)
    map_exp       = { "[" ~ aexp ~ "for" ~ id ~ "in" ~ aexp ~ "]" }    // Map comprehension
    vec_exp       = { "[" ~ aexp ~ ("," ~ aexp)* ~ "]" }               // vector of elements
    ram_exp       = { id ~ "[" ~ aexp ~ "]" }                          // Randm access into a vector
    range_exp     = { range }                                          // Range expression
    app_exp       = { id ~ "(" ~ aexps ~ ")" }                         // Function application
    assert_exp    = { "assert" ~ "(" ~ bexp ~ ")" }                    // Assertion (Prover) expression
    verify_exp    = { "verify" ~ "(" ~ bexp ~ ")"  }                   // Assertion (Verifier) expression
    let_exp       = { "let" ~ id ~ "=" ~ aexp ~ ";" ~ aexp }           // Let expression
    log_exp       = { id ~ "<-" ~ aexp ~ ";" ~ aexp }                  // Transcript log expression
    bin_op        = _{ concat_op | add_op | sub_op | mul_op | div_op | pow_op | dot_op }
aexps = { aexp ~ ("," ~ aexp)* }
stmts   = { aexp ~ (";" ~ aexp)* ~ ";"? }

/// Binary expressions
bexp = { bexp_term ~ (bool_op ~ bexp_term)* }
bexp_term = _{ "(" ~ bexp ~ ")" | not_bexp | app_bexp | eq_bexp | contains_bexp }
    app_bexp = { id ~ "(" ~ aexps ~ ")" }
    eq_bexp  = { aexp ~ "==" ~ aexp  }
    not_bexp = { "!" ~ bexp_term }
    contains_bexp = { aexp ~ "in" ~ aexp }
    bool_op  = _{ and_op | or_op }

/// Type variable declarations
tvar  = { id ~ ":" ~ kind_ty }
tvars = { tvar ~ ("," ~ tvar)* }

/// Function and protocol arguments
arg = { qualifier ~ id ~ ":" ~ typ }
   qualifier = { "public" | "private" }
args = { arg? ~ ("," ~ arg)* }

/// Declarations are either [protocols] or [functions]. Protocols end with a [verify] and functions end with an [AExp]
decl = { proto_decl | func_decl }
    proto_decl = { "proto" ~ id ~ "<" ~ tvars ~ ">" ~ "(" ~ args ~ ")" ~ "where" ~ bexp ~ "{" ~ stmts ~ "}" }
    func_decl  = { "fn" ~ id ~ "<" ~ tvars ~ ">" ~ "(" ~ args ~ ")" ~ "->" ~ typ ~ "{" ~ stmts ~ "}" }

/// Top-level module
decls = { SOI ~ decl* ~ EOI }
