WHITESPACE = _{ " " | "\n" | "\t" }
line_comment = { "//" ~ (!NEWLINE ~ ANY)* }
block_comment = { "/*" ~ ( !"*/" ~ ANY )* ~ "*/" }
COMMENT = _{ line_comment | block_comment }

/// Terminals
positive = @{ ASCII_DIGIT+ }
one = @{ "1" }
two = @{ "2" }
add_op = @{ "+" }
sub_op = @{ "-" }
mul_op = @{ "*" }
div_op = @{ "/" }
pow_op = @{ "^" }
dot_op = @{ "." }
rem_op = @{ "%" }
concat_op = @{ "++" }
eq_op = @{ "==" }
and_op = @{ "&&" }
unary_minus = @{ "-" }

/// Identifiers for functions, variables, type variables
keyword = {"let" | "fn" | "proto" }
id = @{ !(keyword ~ !ASCII_ALPHANUMERIC) ~ (ASCII_ALPHANUMERIC | "_" | "'" )+ }
ids = _{ id ~ ("," ~ id)* }

/// Ranges appear in types and expressions
range = { step_r | unit_r }
    step_r = { size_ty ~ "," ~ size_ty ~ ".." ~ size_ty }
    unit_r = { size_ty ~ ".." ~ size_ty }

/// Type-level size arithmetic
size_ty  = { size_ty_term ~ (size_bin_op ~ size_ty_term)* }
    size_bin_op   = _{ add_op | sub_op | mul_op | div_op | pow_op }
    size_var      = { id }
    size_ty_term  = _{ "(" ~ size_ty ~ ")" | positive | size_var }

/// Base kinds
kind_ty = { field_ty | group_ty | range_ty | pairing_ty | scalar_ty | positive }
    field_ty   = { "Field" }
    group_ty   = { "Group" }
    pairing_ty = { "Pairing" ~ "<" ~ id ~ "," ~ id ~ ">" }
    scalar_ty  = { "Scalar" ~ "<" ~ ids ~ ">" }
    range_ty   = { range }

typ = _{ uni_ty | mle_ty | vec_ty | fin_ty | bool_ty | base_ty }
    base_ty = { id }                                     // Base type variable
    uni_ty  = { "Uni" ~ "<" ~ id ~ "," ~ size_ty ~ ">" }  // Univariate polynomial
    mle_ty  = { "Mle" ~ "<" ~ id ~ "," ~ size_ty ~ ">" }  // Multilinear expression
    fin_ty  = { "Fin" ~ "<" ~ (range | size_ty) ~ ">"  }  // Index type
    vec_ty  = { "[" ~ typ ~ ";" ~ size_ty ~ "]" }         // Vector type
    bool_ty = { "Bool" }                                 // Boolean type

/// Arithmetic expression language of Zippel
exp       = { exp_term ~ (bin_op ~ exp_term)* }
exp_term  = _{
         range_exp
         | "(" ~ exp ~ ")"
         | ifft_exp
         | mle_exp
         | fft_exp
         | poly_exp
         | eval_exp
         | coef_exp
         | challenge_exp
         | random_exp
         | map_exp
         | reduce_exp
         | vec_exp
         | ram_exp
         | pair_exp
         | assert_exp
         | verify_exp
         | let_exp
         | log_exp
         | app_exp
         | bool_exp
         | minus_exp
         | positive
         | id
    }
    ifft_exp      = { "ifft" ~ "(" ~ exp ~ ")"  }                     // Coefficient form (IFFT) univariate polynomial
    fft_exp       = { "fft" ~ "(" ~ exp ~ ")" }                       // Evaluation form (FFT) univariate polynomial or MLE
    poly_exp      = { "poly" ~ "(" ~ exp ~ ")" }                      // Polynomial from coefficients
    eval_exp      = { "eval" ~ "(" ~ exp ~ "," ~ exp ~ ")"}           // Eval polynomial for point
    coef_exp      = { "coef" ~ "(" ~ exp ~ ")"}                       // Given a polynomial return vector of coefficients of polynomial
    mle_exp       = { "mle" ~ "(" ~ exp ~ ")" }                       // Multilinear extension from evaluations over bool hypercube
    random_exp    = { "random" ~ "<" ~ id ~ star? ~ ">" }             // Uniform random sampling (Prover)
    challenge_exp = { "challenge" ~ "<" ~ id ~ star? ~ ">" }          // Random oracle challenge (Verifier)
    map_exp       = { "[" ~ exp ~ "for" ~ id ~ "in" ~ exp ~ "]" }     // Map comprehension
    reduce_exp    = { "reduce" ~ "(" ~ bin_op ~ "," ~ exp ~ ")" }     // Reduce operation (left)
    vec_exp       = { "[" ~ exp ~ ("," ~ exp)* ~ "]" }                // vector of elements
    ram_exp       = { id ~ "[" ~ exp ~ "]" }                          // Randm access into a vector
    pair_exp      = { "pair" ~ "(" ~ exp ~ "," ~ exp ~")" }           // Billinear pairing operation
    range_exp     = { range }                                         // Range expression
    assert_exp    = { "assert" ~ "(" ~ exp ~ ")" }                    // Assertion (Prover) expression
    verify_exp    = { "verify" ~ "(" ~ exp ~ ")"  }                   // Assertion (Verifier) expression
    app_exp       = { id ~ "(" ~ exps ~ ")" }                         // Function application
    let_exp       = { "let" ~ id ~ "=" ~ exp ~ ";" ~ exp }            // Let expression
    log_exp       = { id ~ "<-" ~ exp ~ ";" ~ exp }                   // Transcript log expression
    bool_exp      = { "true" | "false" }                              // True or false constants
    minus_exp     = _{ unary_minus ~ exp }                            // Negative expressions
    bin_op        = _{ concat_op | add_op | sub_op | mul_op | div_op | pow_op | dot_op | rem_op | eq_op | and_op }
exps = { exp ~ ("," ~ exp)* }
stmts   = { exp ~ (";" ~ exp)* ~ ";"? }

/// Type variable declarations
tvar  = { id ~ ":" ~ kind_ty }
tvars = { tvar ~ ("," ~ tvar)* }

/// A scalar must be non-zero
star = { "*" }

/// Function and protocol arguments
arg = { qualifier? ~ distribution? ~ id ~ ":" ~ typ }
   qualifier = { public | private }
   public = { "public" }
   private = { "private" }
   distribution = { "uniform" ~ star? }
args = { arg? ~ ("," ~ arg)* }

/// Declarations are either [protocols] or [functions].
decl = { proto_decl | func_decl }
    proto_decl = { "proto" ~ id ~ "<" ~ tvars ~ ">" ~ "(" ~ args ~ ")" ~ "where" ~ exp ~ "{" ~ stmts ~ "}" }
    func_decl  = { "fn" ~ id ~ "<" ~ tvars ~ ">" ~ "(" ~ args ~ ")" ~ "->" ~ typ ~ "{" ~ stmts ~ "}" }

/// Top-level module
decls = { SOI ~ decl* ~ EOI }
